### ISSUE TITLE
Vortex doesn't work at all (.NET Runtime Error)

### ISSUE THREAD

**Issue by that404nerd** [sonic2kk/steamtinkerlaunch#1250]
As the title mentions vortex doesn't want to work at all. I just installed vortex using STL and didn't touch anything and when i launch it this is what I get:

<img width="1216" height="631" alt="Image" src="https://github.com/user-attachments/assets/d1b7c1f6-3f69-4766-91a0-9747b9cc7d26" />

**ALSO I AM USING STEAMTINKERLAUNCH v14.0.20250602 (steamtinkerlaunch-git) FROM THE AUR**

Clicking on fix downloads the runtime executable but after the download's finished it shows the same error over and over again. It happened first in Manjaro but recently i installed another distro (CachyOS) and the same thing happens. It's so annoying because the native Linux App is far from perfect and I manage collections as well. 

The exe file it downloaded was `vortex-setup-1.14.8.exe`. Could it be the vortex version? I have no idea. Please look into this issue. Thanks and have a nice day!

**Comment by sonic2kk** [comment]
I don't use Vortex, but have you confirmed that this is something SteamTinkerLaunch can fix and not a Wine compatibility issue? All SteamTinkerLaunch does is install and run Vortex using Wine, with a little bit of extras to help make using games across drives a bit easier.

Perhaps installing .NET 8.0 manually could help? Does .NET 8.0 work with Wine?

> Please look into this issue.

There's not a whole lot I can go off of here, especially since the issue template that you selected was ignored, so no log files have been given that might hint at what is going wrong.

**Comment by that404nerd** [comment]
> I don't use Vortex, but have you confirmed that this is something SteamTinkerLaunch can fix and not a Wine compatibility issue? All SteamTinkerLaunch does is install and run Vortex using Wine, with a little bit of extras to help make using games across drives a bit easier.
> 
> Perhaps installing .NET 8.0 manually could help? Does .NET 8.0 work with Wine?
> 
> > Please look into this issue.
> 
> There's not a whole lot I can go off of here, especially since the issue template that you selected was ignored, so no log files have been given that might hint at what is going wrong.

Not a wine related issue, not at all. I tried installing dotnet manually using winetricks but it didnt work at all. Tried some other stuff but yea it didnt work too. Even trying to manually install that thing doesnt work. Currently not at the computer but i will send the logs soon. Thanks!

**Comment by sonic2kk** [comment]
> Not a wine related issue, not at all. I tried installing dotnet manually using winetricks but it didnt work at all.

If it didn't work with Winetricks, this suggests to me that it _is_ a Wine issue. You seem confident that it isn't related to Wine so I'm just trying to ascertain where that confidence comes from, as it seems here that if manual intervention doesn't fix it then I'm not sure how SteamTinkerLaunch could.

I should also be clearer that, it could be a specific feature of Vortex most likely related to .NET 8.0 or the checking of the .NET 8.0 installation that does not work with Wine.

**Comment by Matrice1312** [comment]
currently looking into this aswell and it is a Vortex Issue, but there is a manual fix, by putting the hostfxr.dll into the C:programfiles/black tree gaming/vortex/app.asar.unpacked.assets/ it should fix the .net error.

~~the actual issue is related to an outdated vortex issue since Vortex's latest version does work with Wine/Proton.~~

actual issue is that due to the way steamtinker launch runs vortex on its own seperate pfx but forgets to install the proper winetricks packages to the "Vortex pfx" located at /home/$USERNAME/.config/steamtinkerlaunch/vortex/compatdata/pfx/ so a manual intervention would be needed in its current state.

**Comment by that404nerd** [comment]
> currently looking into this aswell and it is a Vortex Issue, but there is a manual fix, by putting the hostfxr.dll into the C:programfiles/black tree gaming/vortex/app.asar.unpacked.assets/ it should fix the .net error.
> 
> ~the actual issue is related to an outdated vortex issue since Vortex's latest version does work with Wine/Proton.~
> 
> actual issue is that due to the way steamtinker launch runs vortex on its own seperate pfx but forgets to install the proper winetricks packages to the "Vortex pfx" located at /home/$USERNAME/.config/steamtinkerlaunch/vortex/compatdata/pfx/ so a manual intervention would be needed in its current state.

So i have to manually download the dll file and place it there? And the folder is actually in C:programfiles/black tree gaming/vortex/resources/app.asar.unpacked/assets.

Update: I placed the .dll file and it doesn't complain about the missing dll file but it still doesn't work at the dotnet missing. Again downloading it doesn't work.

<img width="665" height="155" alt="Image" src="https://github.com/user-attachments/assets/17f4e15f-61bd-4ae9-8e37-c5d4683e5bcc" />

**Comment by Matrice1312** [comment]
Vortex downloads the setup for you when you click "fix" you want to go to that file that you downloaded and using winetricks run the .exe vortex provides under this prefix --> /home/$USERNAME/.config/steamtinkerlaunch/vortex/compatdata/pfx/.

**Comment by that404nerd** [comment]
`WINEPREFIX=~/.config/steamtinkerlaunch/vortex/compatdata/pfx wine windowsdesktop-runtime-6.0.26-win-x64.exe` like this? or should `WINEPREFIX=~/.config/steamtinkerlaunch/vortex/compatdata/pfx winetricks` and run the exe from that dialog box?

**Comment by Matrice1312** [comment]
should be

**Comment by that404nerd** [comment]
Hmm still shows the same issue. Idk what's wrong at this point
Edit: Can you please try it by yourself? Maybe see if it works on your side

**Comment by that404nerd** [comment]
Any way to fix that?

**Comment by OrangeDuckNTL** [comment]
I'm having the same issue.

**Comment by Gatsu166** [comment]
Okay so I think i found a solution, you will need to uninstall all dotnet installs using this method.

run: "./steamtinkerlaunch vortex winetricks"

Use the "uninstall apps" option.

Remove all .NET installs (including 8.0)

After this you will close out the dialogue box and run "./steamtinkerlaunch vortex winetricks" again.

This time pick to configure DLLs and pick out .NET 6.0 from the list. run all the installers that come up.

Test and hope that it works!

**Comment by that404nerd** [comment]
> Okay so I think i found a solution, you will need to uninstall all dotnet installs using this method.
> 
> run: "./steamtinkerlaunch vortex winetricks"
> 
> Use the "uninstall apps" option.
> 
> Remove all .NET installs (including 8.0)
> 
> After this you will close out the dialogue box and run "./steamtinkerlaunch vortex winetricks" again.
> 
> This time pick to configure DLLs and pick out .NET 6.0 from the list. run all the installers that come up.
> 
> Test and hope that it works!

Thanks! It works. I fresh installed vortex and selected configuring the dlls and selected dotnet6 as you mentioned. Thank you so much!

@sonic2kk Please see if this problem can be patched using this method. Thanks!

**Comment by sonic2kk** [comment]
I would gladly accept a community contribution on this! I have no interest in supporting Vortex myself at this moment, but would happily review a PR to implement the needed fix in this PR (which sounds like it needs `dotnet6` to be installed with Winetricks during installation).

**Comment by that404nerd** [comment]
Look like i have yet another issue with opening mod pages from vortex. Trying to click on the update button from vortex doesnt open the mod page. I cant open any link from vortex. Downloading mods from the browser is working as expected. Please look into this too. Thanks!

**Comment by sonic2kk** [comment]
Again, this is not something that I will be fixing, and asking for something to be looked into with only a brief description and no further details can make this tricky to track down. This could be a Wine bug once again, there doesn't seem to be confirmation here that it isn't a Wine bug. The issue reported here _is_ due to a Wine bug/unimplemented functionality, so the same could be happening here. Some kind of Winetricks package could fix it perhaps.

As with the initial problem reported in this issue, a PR would be welcome to implement a fix, but I will not be working on it as I do not use Vortex.

**Comment by that404nerd** [comment]
> Again, this is not something that I will be fixing, and asking for something to be looked into with only a brief description and no further details can make this tricky to track down. This could be a Wine bug once again, there doesn't seem to be confirmation here that it isn't a Wine bug. The issue reported here _is_ due to a Wine bug/unimplemented functionality, so the same could be happening here. Some kind of Winetricks package could fix it perhaps.
> 
> As with the initial problem reported in this issue, a PR would be welcome to implement a fix, but I will not be working on it as I do not use Vortex.

Wierd... It works now. Looks like it's some random bug ig. I didn't do anything and it just works all of a sudden.

**Comment by sunbro626** [comment]
> > Okay so I think i found a solution, you will need to uninstall all dotnet installs using this method.
> > run: "./steamtinkerlaunch vortex winetricks"
> > Use the "uninstall apps" option.
> > Remove all .NET installs (including 8.0)
> > After this you will close out the dialogue box and run "./steamtinkerlaunch vortex winetricks" again.
> > This time pick to configure DLLs and pick out .NET 6.0 from the list. run all the installers that come up.
> > Test and hope that it works!
> 
> Thanks bud! It works. I fresh installed vortex and selected configuring the dlls and selected dotnet6 as you mentioned. Thank you so much!
> 
@that404nerd  im having a similar issue, could you post a more detailed set of instructions (such as what exactualy is ment by ' run:"./steamtinkerlaunch vortex winetricks" ')

**Comment by that404nerd** [comment]
> > > Okay so I think i found a solution, you will need to uninstall all dotnet installs using this method.
> > > run: "./steamtinkerlaunch vortex winetricks"
> > > Use the "uninstall apps" option.
> > > Remove all .NET installs (including 8.0)
> > > After this you will close out the dialogue box and run "./steamtinkerlaunch vortex winetricks" again.
> > > This time pick to configure DLLs and pick out .NET 6.0 from the list. run all the installers that come up.
> > > Test and hope that it works!
> > 
> > 
> > Thanks bud! It works. I fresh installed vortex and selected configuring the dlls and selected dotnet6 as you mentioned. Thank you so much!
> 
> [@that404nerd](https://github.com/that404nerd) im having a similar issue, could you post a more detailed set of instructions (such as what exactualy is ment by ' run:"./steamtinkerlaunch vortex winetricks" ')

Sorry for the late reply! But here's how to fix it:

- Make sure to install vortex first, it will complain about dotnet when it first launches. Close vortex and follow these steps below.

First open the terminal and type this:
`WINEPREFIX=~/.config/steamtinkerlaunch/vortex/compatdata winetricks`

It will open a window, in that select "Select the default wineprefix"
Then select "Install a Windows DLL or Component"

You will see a list of windows compoenents, scroll down and select these:
`dotnet6`
`dotnetdesktop6`

After you selected those, click OK and then try to launch steamtinkerlaunch again. Vortex should work without issues. That's pretty much it

**Comment by princeepicgamer** [comment]
> > > > Okay so I think i found a solution, you will need to uninstall all dotnet installs using this method.
> > > > run: "./steamtinkerlaunch vortex winetricks"
> > > > Use the "uninstall apps" option.
> > > > Remove all .NET installs (including 8.0)
> > > > After this you will close out the dialogue box and run "./steamtinkerlaunch vortex winetricks" again.
> > > > This time pick to configure DLLs and pick out .NET 6.0 from the list. run all the installers that come up.
> > > > Test and hope that it works!
> > > 
> > > 
> > > Thanks bud! It works. I fresh installed vortex and selected configuring the dlls and selected dotnet6 as you mentioned. Thank you so much!
> > 
> > 
> > [@that404nerd](https://github.com/that404nerd) im having a similar issue, could you post a more detailed set of instructions (such as what exactualy is ment by ' run:"./steamtinkerlaunch vortex winetricks" ')
> 
> Sorry for the late reply! But here's how to fix it:
> 
>     * Make sure to install vortex first, it will complain about dotnet when it first launches. Close vortex and follow these steps below.
> 
> 
> First open the terminal and type this: `WINEPREFIX=~/.config/steamtinkerlaunch/vortex/compatdata winetricks`
> 
> It will open a window, in that select "Select the default wineprefix" Then select "Install a Windows DLL or Component"
> 
> You will see a list of windows compoenents, scroll down and select these: `dotnet6` `dotnetdesktop6`
> 
> After you selected those, click OK and then try to launch steamtinkerlaunch again. Vortex should work without issues. That's pretty much it

ok so i put in the `WINEPREFIX=~/.config/steamtinkerlaunch/vortex/compatdata winetricks` and it just says warning wineserver not found  and gives me nothing else
