### ISSUE TITLE
⚠ [Help wanted] Vortex Compatibility Testing

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#555]
Been spending some time trying to debug some issues I'm having with Vortex. I can't get it to launch at all with SteamTinkerLaunch and I can't seem to get any useful debugging output. When trying to launch for Vortex executable manually from the command line with `WINEPREFIX=/home/blah/.config/steamtinkerlaunch/vortex/compatdata/pfx /home/blah/.local/share/Steam/compatibilitytools.d/GE-Proton7-29/files/bin/wine Vortex.exe` it launches perfectly fine.

Is there a way to get further logging about what's going wrong with Vortex and Wine? The `steamtinkerlaunch.log` and `installDotNet` logs don't have anything useful, as dotnet seems to install fine (though Vortex prompts when I launch it that it needs DotNet6 and then seemingly installs it fine?) and the steamtinkerlaunch log just  says "starting vortex with no commands"  and then  "vortex exited". Running `steamtinkerlaunch vortex start` from the command line doesn't  produce  any real output either.

I've kind of hit a wall here. Vortex seems to work without SteamTinkerLaunch but won't open when I try to open it from SteamTinkerLaunch. Anyone know what the problem could be?

**Comment by frostworx** [comment]
[It looks like](https://github.com/frostworx/steamtinkerlaunch/issues/551#issuecomment-1227570421) Vortex no longer works in steamtinkerlaunch _(or the dotnet 4 installation used conflicts with some _(wip?))_ dotnet6 implementation)_
Either way I won't find the time and motivation to fix this issuee, because I don't use Vortex at all.
I'll help anybody interested in submitting a PR to fix this when possible.

**Comment by sonic2kk** [comment]
Seems like Vortex is making an effort to target Wine, with the move to DotNet 6 actually making Vortex work out of the box with Wine 7.15  :open_mouth: https://github.com/Nexus-Mods/Vortex/issues/10686#issuecomment-1219083544

As that issue primarily mentions targeting Lutris, I'm not sure what the situation is for installing with Proton. But that issue is worth looking at for anyone that wants to take a look at the issue. Seems like Vortex in future could just need a specific path variable set and a reasonably up-to-date Wine version!

**Comment by frostworx** [comment]
ah nice. I've partially seen that thread, because the one person showing off their lutris script _(or something similar)_ pinged me for doubtful reasons. haven't read the originally intended context of the thread though.

**Comment by frostworx** [comment]
crazy idea, but if vortex installs dotnet6 itself automatically correctly, it might be worth to test if the problem persist, if the dotnet install functions are commented out.

**Comment by sonic2kk** [comment]
This is actually something I was planning on trying haha, haven't gotten around to it as I'm working on a couple of other things but I could also see that working.

When launching Vortex with `WINEPREFIX=/home/blah/.config/steamtinkerlaunch/vortex/compatdata/pfx /home/blah/.local/share/Steam/compatibilitytools.d/GE-Proton7-29/files/bin/wine Vortex.exe` after installing from STL, it gave me the same prompt mentioned in [this comment](https://github.com/frostworx/steamtinkerlaunch/issues/551#issuecomment-1227570421) on another STL issue. However whenever I clicked "Fix", Vortex downloaded and installed DotNet6. When I restarted I was able to navigate the Vortex UI, I didn't try installing mods though, and Vortex still didn't launch from SteamTinkerLaunch.

I'm wondering if maybe STL trying to install dotnet48 (as it was previously required) messes up Vortex installing DotNet6, if it tries to install it itself at all. It might also be worth trying to get STL to export the `DOTNET_ROOT` (as mentioned in the earlier linked Vortex issue). Though I'm not sure, I guess this is meant to point to where DotNet6 is installed in the Wine prefix?

**Comment by frostworx** [comment]
> I'm wondering if maybe STL trying to install dotnet48 (as it was previously required) messes up Vortex installing DotNet6

yeah, that's what I wanted to suggest. I'd guess as well that DOTNET_ROOT should point to a dotnet6 intallation.
so a clean automated approach would probably be either

- install dotnet6 via vortex _(assuming it works as expected)_ and reproduce that installation with to-be written functions in steamtinkerlaunch  _(ideally with some shared destination)_ and point DOTNET_ROOT to that dir
or
- check if vortex offers some command line option to automatically install dotnet6 if missing without popping up the requester at all

**Comment by sonic2kk** [comment]
Going to take a stab at fixing this over the weekend. Famous last words :-) I'll report back with anything I find out. I'll start by not installing DotNet6 at all and setting DOTNET_ROOT, and take things from there. We could run into a few issues since this might only work with very new versions of Wine - Wine 7.15, released August 19th, is the only one I've seen reports of working. I would say GE-Proton will have relevant patches eventually for this if it doesn't already.

If Vortex is starting to target Wine then in time hopefully the days of Vortex breakages will behind us soon :-)

**Comment by sonic2kk** [comment]
Even when trying to use system Wine (7.15) manually, I can't get Vortex to see the DotNet 6 installation :frowning:

**Comment by frostworx** [comment]
the days of Vortex breakages will never be behind us. dotnet is only one of multiple possible issues. have fun either way.

**Comment by ghost** [comment]
> ah nice. I've partially seen that thread, because the one person showing off their lutris script _(or something similar)_ pinged me for doubtful reasons. haven't read the originally intended context of the thread though.

@frostworx :smile: 

> Going to take a stab at fixing this over the weekend. Famous last words :-) I'll report back with anything I find out. I'll start by not installing DotNet6 at all and setting DOTNET_ROOT, and take things from there. We could run into a few issues since this might only work with very new versions of Wine - Wine 7.15, released August 19th, is the only one I've seen reports of working. I would say GE-Proton will have relevant patches eventually for this if it doesn't already.
> 
> If Vortex is starting to target Wine then in time hopefully the days of Vortex breakages will behind us soon :-)

@sonic2kk I have gotten Vortex 1.6.8 working in the default wine prefix by doing the following:

I tested this on a clean prefix and on my used default prefix.
1. Add .NET 4.8 Framework to the prefix via winetricks
   Default prefix: `winetricks dotnet48`.
   Custom prefix: `env WINEPREFIX="/your/pfx/" winetricks dotnet48`
2. Add [.NET 6 Runtime to the prefix via the executable installer](https://download.visualstudio.microsoft.com/download/pr/b4a17a47-2fe8-498d-b817-30ad2e23f413/00020402af25ba40990c6cc3db5cb270/windowsdesktop-runtime-6.0.8-win-x64.exe)
   Default prefix: Launch it with the "Wine Windows Program Loader" or `wine start windowsdesktop-runtime-6.0.8-win-x64.exe`.
   Custom prefix: `env WINEPREFIX="/your/pfx/" wine start windowsdesktop-runtime-6.0.8-win-x64.exe`
   <details><summary>Running the installers and .NET Framework && .NET Runtime</summary>
   
   The application loader uses `wine start /unix`, but the /unix option makes no difference to the installers or Vortex.
   The above link I provided is from the [official .NET changelog for 6.0.8](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.8/6.0.8.md#downloads) and is also a [slightly newer link than the download used in Vortex as of writing this](https://github.com/Nexus-Mods/Vortex/blob/c70c502ed6c9219da62e3292734ca1ed4e17e20a/src/extensions/installer_fomod/constants.ts#L6-L7).
   [Per microsoft,](https://dotnet.microsoft.com/en-us/download/dotnet/6.0#runtime-desktop-6.0.8)
   > The .NET Desktop Runtime enables you to run existing Windows desktop applications. This release includes the .NET Runtime; you don't need to install it separately.
   
   The above installer includes runtime/host but not the .NET Framework. Unfortunately, the dotnet framework is still required by Vortex and is not provided by the latest installers. .NET 6 is therefore essentially another dependency on top of dotnet 4.8, which provides the framework. Vortex will complain about a missing or broken dotnet installation without both the .NET Framework and .NET Runtime since they are shipped separately. ~~thanks Microsoft.~~
   </details>
3. Run [vortex-setup-1.6.8.exe](https://github.com/Nexus-Mods/Vortex/releases/download/v1.6.8/vortex-setup-1.6.8.exe) or [whatever the latest release is](https://github.com/Nexus-Mods/Vortex/releases/latest).
   Default prefix: Launch it with the "Wine Windows Program Loader" or `wine start vortex-setup-1.6.8.exe`
   Custom prefix: `env WINEPREFIX="/your/pfx/" wine start vortex-setup-1.6.8.exe`
4. When Vortex finishes loading it will complain about a broken dot net installation, [or even indicate the native linux runtime was selected](https://github.com/Nexus-Mods/Vortex/issues/10686#issuecomment-1218520836). Ignore Vortex's struggling and select the quit option when prompted or close Vortex yourself.
   <details><summary>fix prompt?</summary>
   
   Vortex will run the installer when using the provided fix button, but will continue complaining about the missing/broken .NET after installing and reopening since it is still looking in the wrong place by default. You need step 5 to fix that. Since Vortex also uses an older link for .NET 6, I opted to recommend these steps instead. It's just better to fix it before Vortex prompts the user.
   </details>
5. We will now use the previously mentioned environment variable `DOTNET_ROOT` to negate the error.
   Default prefix:
   ```bash
   env DOTNET_ROOT="c:\Program Files\dotnet\\" wine start /d "c:\Program Files\Black Tree Gaming Ltd\Vortex" Vortex.exe
   ```
   Custom prefix:
   ```bash
   env WINEPREFIX="/your/pfx/" DOTNET_ROOT="c:\Program Files\dotnet\\" wine start /d "c:\Program Files\Black Tree Gaming Ltd\Vortex" Vortex.exe
   ```
   The above paths are relative to the wine prefix which guarantees the .NETs we just installed are selected.
   ~~in dos land case sensitivity doesn't exist for paths so c: is C:, still so cursed everytime writing a command like this, smh~~ 
   You now have Vortex running with the appropriate .NET.
   No errors should appear on startup. :clap: 
   
Also, [I have been contributing directly to Vortex and gotten the development environment building on Linux.](https://github.com/Nexus-Mods/Vortex/issues/2862#issuecomment-1219782154)
A native linux package of Vortex has a non-zero chance of occurring, which may obsolete all of this.

**Comment by sonic2kk** [comment]
Holy heck! Thank you so much for the detailed writeup and excellent news!

So the `dotnet48` winetrick is still required, gotcha. I understand the consensus is that DotNet 6 installs and Vortex works with Wine 7.15, though STL is currently set up afaik to use a user-selected version of Wine as I believe the version of Wine used to run Vortex is also the version used to run the game once its launched. I'm aware there are no guarantees that your steps will work with, say, GE-Proton7-30, but I will try them nonetheless if nothing else but out of morbid curiosity :smile: 

(If it still requires `dotnet48`, I wonder if #549 (which seems to be Steam Deck only) is unrelated to this. There are other reports of Winetricks not working on Steam Deck so it could be an entirely unrelated matter?)

> Also, I have been contributing directly to Vortex and gotten the development environment building on Linux. A native linux package of Vortex has a non-zero chance of occurring, which may obsolete all of this.

Assuming a native Linux Vortex package appears and works with installing mods for games running through Proton, this would probably obsolete all of this - but imo that would be a *very* worthy successor to the hoops we currently jump through to install and use Vortex on Linux with Wine. Personally I would be very happy to see a native Linux Vortex and have STL integrate with that. Perhaps that could even allow for better integration on Steam Deck and maybe even STL running through Flatpak Steam!

Of course I understand that isn't a guarantee that a native Linux build will appear, so for the meantime, looking into getting Vortex working with Wine again is probably fine. A native Linux package once it appears will need testing too but as mentioned if a package did come along and obsolete this, I'd be perfectly happy with that :slightly_smiling_face: 

Thanks for outlining the steps needed. I'll see if I can implement this into STL once I have a moment (of course anyone else that wants to contribute is welcome to, as I am in-between PRs here and working on adding STL to ProtonUp-Qt). And also a big thanks for your efforts on trying to improve the Linux Vortex experience upstream :+1:

**Comment by SeongGino** [comment]
So basically, in a legitimate (and largely successful) attempt at making Vortex Linux-friendly, the change has subsequently *broken* its behavior on Linux environments with a pre-existing `dotnet-host`.

This. Is. *Hilarious.* XD

...a-Anyways--I found that prepending the env var `DOTNET_ROOT="c:\Program Files\dotnet\\"` before the `steamtinkerlaunch vortex start` command works *in a terminal,* but same method doesn't seem to work in the context of a .desktop starter. I'm assuming that's simply a limitation of XDG app files, but mayhaps STL might wanna export this value itself in the future?

Guess we can add this along with Halo MCC in the top 10 Linux Oopsies for this year, of games that try to support the platform only to cause *more* unintended issues. I am laughing at this more than I should, but it is also genuinely appreciated to see progress like this in embracing Linux for game modding.

*Though, if Vortex is to be made a native app, I do hope it'll have some way of forking off utility processes in Wine, since a lot of Skyrim animation mods rely on Nemesis, it and FO4 use BodySlide for models, others using xEdit (which currently doesn't work for texture generation in Wine???), and so on.

**Comment by sonic2kk** [comment]
> Though, if Vortex is to be made a native app, I do hope it'll have some way of forking off utility processes in Wine

I also hope this to be the case for the exact reasons you outlined. Being able to run Nemesis and BodySlide was essential when I used MO2 to mod Skyrim SE.

> I found that prepending the env var DOTNET_ROOT="c:\Program Files\dotnet\\" before the steamtinkerlaunch vortex start command works in a terminal, but same method doesn't seem to work in the context of a .desktop starter

Adding variables like this in a `.desktop` file can be really finicky because of how escape characters work I believe. At least in my experience this has been a massive headache. For one of my own projects I had to do something like this:

```
Exec=env WINEPREFIX="/home/user/Downloads/WineApp/pfx" wine C:\\\\users\\\\user\\\\AppData\\\\Roaming\\\\Microsoft\\\\Windows\\\\Start\\ Menu\\\\Programs\\\\App\\ Space\\ Name.lnk
```

**Comment by ghost** [comment]
> So basically, in a legitimate (and largely successful) attempt at making Vortex Linux-friendly, the change has subsequently _broken_ its behavior on Linux environments with a pre-existing `dotnet-host`.

No attempt was made based on .NET version change alone? Vortex changing .NET version seems largely separate from the status of building on non-windows platforms, let alone running in WINE.

> ...a-Anyways--I found that prepending the env var `DOTNET_ROOT="c:\Program Files\dotnet\\"` before the `steamtinkerlaunch vortex start` command works _in a terminal,_ but same method doesn't seem to work in the context of a .desktop starter. I'm assuming that's simply a limitation of XDG app files, but mayhaps STL might wanna export this value itself in the future?

The Exec key does not provide variable assignment like a shell. You need to use `env` to add the variable, then the command.

> Adding variables like this in a `.desktop` file can be really finicky because of how escape characters work I believe. At least in my experience this has been a massive headache. For one of my own projects I had to do something like this:

The problem lies in the `Exec` key's escape logic.
In the [Desktop Entry Spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables),
> to unambiguously represent a literal backslash character in a quoted argument in a desktop entry file requires the use of four successive backslash characters ("\\\\\\\\").

So you've gotta spam those or write your command into a field which will populate those slashes for you, like the properties menu of a desktop entry in Dolphin (plasma desktop's file manager). It's really not too much trouble. For example, [I wrote a whole shell script into the Exec key of my desktop entry.](https://github.com/NicBOMB/Vortex/blob/b447eb956eb95f25887b8ec97398dd870480d32e/vortex-lutris-installer.yml#L502-L504)

Try `Exec=env DOTNET_ROOT='c:\\\\Program Files\\\\dotnet\\\\' steamtinkerlaunch vortex start`

**Comment by SeongGino** [comment]
> No attempt was made based on .NET version change alone? Vortex changing .NET version seems largely separate from the status of building on non-windows platforms, let alone running in WINE.

I was just making an observation as a mere user, was all. It's half-joking.

> So you've gotta spam those or write your command into a field which will populate those slashes for you, like the properties menu of a desktop entry in Dolphin (plasma desktop's file manager).

Today I Learned:tm:. That's what I'd guessed, but good to have a source on that as well, thank you.

**Comment by Arcitec** [comment]
Initial install in STL in the Steam Flatpak was easy. STL successfully installed dotnet48 and then Vortex.

Fun fact. DotNet6 runs for me. I just had to run Vortex with GE-Proton 7-31. On first start Vortex gave me a "message log" popup with some error about a missing DotNet DLL and a button to Fix it. (That EXACT same dialog with same text shows up on Windows too.)

Clicking Fix made me briefly see a DotNet window which vanished quickly. I guess Vortex triggers a silent install.

On next launch of Vortex, there was no more warning and the app runs normally.

But... I got a notification on Vortex saying that Hardlinks mode has been removed from the app and that it wanted to fix my settings. I clicked fix and it switched to softlink mode. I went back into settings and tried to change Deployment Mode and Vortex only has softlinks, no other modes.

When I look in the game folder it seems like there are no mod links/files in there.

**Comment by sonic2kk** [comment]
> Fun fact. DotNet6 runs for me. I just had to run Vortex with GE-Proton 7-31

Ah! 7-31 has a Wine update so perhaps that could be related!

> But... I got a notification on Vortex saying that Hardlinks mode has been removed from the app and that it wanted to fix my settings. I clicked fix and it switched to softlink mode. I went back into settings and tried to change Deployment Mode and Vortex only has softlinks, no other modes.
> 
> When I look in the game folder it seems like there are no mod links/files in there.

I'm not totally sure what this means as I don't use Vortex but this could be related to Flatpak. Did Vortex remove your mods or is it just not seeing them now?

**Comment by Arcitec** [comment]
@sonic2kk 

> Did Vortex remove your mods or is it just not seeing them now?

Vortex lists my installed mods for the game (Mods I have installed VIA Vortexx), but it doesn't place the mods in the game's folder. I think this is because it's trying to make symlinks instead of hardlinks (STL's wiki says that hardlinks are the only method that works on Linux). So if Vortex has removed hardlinks, which it seems like, then that is bad news for us.

**Comment by sonic2kk** [comment]
Ah, I understand now. So Vortex itself has removed support for this kind of mod, and this feature being missing isn't a bug on STL's side. But still it means currently Vortex mods don't work, which is not good news.

I wonder why symlinks don't work and if this is something Vortex could fix on their side.

**Comment by Arcitec** [comment]
Yep. But it might be possible to make soft symlinks work on Wine... Or to edit Vortex config to force it to use old hardlink method (it cannot be selected via its GUI but maybe it still has code for it).

**Comment by ghost** [comment]
> I wonder why symlinks don't work and if this is something Vortex could fix on their side.

[This is why](https://github.com/Nexus-Mods/Vortex/issues/9629#issuecomment-1013658187).

**Comment by ghost** [comment]
> But... I got a notification on Vortex saying that Hardlinks mode has been removed from the app and that it wanted to fix my settings. I clicked fix and it switched to softlink mode. I went back into settings and tried to change Deployment Mode and Vortex only has softlinks, no other modes.

This is inaccurate. Hardlink mode is still present. 
You were simply warned that Vortex cannot deploy your mods. You may need to change your mod staging folder to a location on the same drive as the game.
In the Vortex settings->mods->mod staging folder
use a path like 
`Z:\path\to\Storage\Vortex Mods\{GAME}\mods`
where the real mount path is
`/path/to/Storage`
I am still using Hardlink Deployment for multiple games.
What game were you trying to deploy mods to?

**Comment by frostworx** [comment]
If you look a bit closer, steamtinkerlaunch already takes care that the staging dir is on the same partition as the game is, so
messing around manually is not required when using it (when it works again 😏...)

`steamtinkerlaunch` prepares one `VORTSETCMD` cmd _(`VORTSETCMD="$STLSHM/vortset.cmd"`)_
by adding all vortex configuration options "required" for every game found, including the staging dir found.
Depending on the list of installed, compatible games, this file can become pretty big.

When done, this file is run once within the vortex prefix to set up all games without any further user-configuration.
This worked fine before, so if it no longer does something changed, apparently.
Likely `VORTSETCMD` has some hints which variable/path broke.

**Comment by frostworx** [comment]
just ran `DOTNET_ROOT="c:\\Program Files\\dotnet\\\\" steamtinkerlaunch vortex start` _(didn't test if the variable had an effect)_
with a clean ~/.config/steamtinkerlaunch/
after ~7 minutes Vortex opened _(`vortset.cmd` had >170 lines which look fine so far)_
After clicking the new fix, dotnet6 seems to have installed correctly _(haven't compared the before/after compadata)_.
Unfortunately, unlike before, no of the detected games was set as "managed" automatically, but I was able to add Fallout4 by clicking manage. It kept its autoconfigured hardlink path as valid.
Doesn't look **THAT** broken than what I have expected after this long discussion _(sorry, haven't read everything)_
@ modders, I'd suggest you try to reproduce this and see if a managed game actually can be modded or not.
Maybe the issue just requires a tiny fix.
good luck so far!

edit:
`Vortex.exe --set settings.mods.activator.fallout4="\"hardlink_activator\""`
_(cut from the autocreated `vortset.cmd`)_ no longer seems to work, maybe the escaped quotes need to be removed _(again?)_

`steamtinkerlaunch vortex getset` still also outputs 
`settings.mods.activator.fallout4 = "hardlink_activator"` _(after having it set to managed manually above)_, so the option seems to be unmodified otherwise.

**Comment by frostworx** [comment]
fyi _(update [from here](https://github.com/frostworx/steamtinkerlaunch/issues/589#issuecomment-1255245846))_:

Apparently I wasn't able to express correctly what I wanted to say with my last two comments in #555 _(explains the silence following 😀)_
I do not think that it is broken very much.
Likely only three fixes are required to get it completely working again as it worked before:
- simply set `DOTNET_ROOT` within `steamtinkerlaunch` _(seems to work as expected, thx for the hint @NicBOMB)_
- proton GE should be used automatically, but I need to add a fix that the latest version is automatically downloaded when none is found _(this is definitely broken and requires a fix in `createDLProtList` - likely it requires a similar fix for the github changes @sonic2kk added with this [PR](https://github.com/frostworx/steamtinkerlaunch/pull/592) - will need more time than initially expected, but I'll fix it asap)_
- Vortex might have changed some quoting, which needs to be adjusted again in `vortset.cmd` creation. this is definitely the biggest problem, I already suspected above _(although likely just needs a minor fix when found out where 🤨)_ - likely won't happen very soon

**Comment by frostworx** [comment]
I'll also add an automatic installer for dotnet6 (recycling the vortex download if available and downloading it automatically otherwise). Seems like the "Fix" button installation does not always work reliably _(it is dotnet, so expected)_ and Vortex will loop in a FIX -> Install loop. I hope by installing dotnet before we have the chance to workaround this issue somehow.

**Comment by ghost** [comment]
> I'll also add an automatic installer for dotnet6 (recycling the vortex download if available and downloading it automatically otherwise). Seems like the "Fix" button installation does not always work reliably _(it is dotnet, so expected)_ and Vortex will loop in a FIX -> Install loop. I hope by installing dotnet before we have the chance to workaround this issue somehow.

This may be helpful for installing dotnet 6 before Vortex https://github.com/NicBOMB/Vortex/blob/wine-installer/installer-scripts/vortex-installer.sh

**Comment by frostworx** [comment]
Thanks, @NicBOMB but too late 🤓
Already added it just right now with above commit

edit: hah, forgot to look for and add the silent flag. Thanks. Saves me searching 😀

**Comment by ghost** [comment]
> Thanks, @NicBOMB but too late nerd_face Already added it just right now with above commit
> 
> edit: hah, forgot to look for and add the silent flag. Thanks. Saves me searching grinning

You should download the latest installer ([6.0.9](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.9/6.0.9.md)) instead of 6.0.6. Links can be found in sub-directories here https://github.com/dotnet/core/tree/main/release-notes/6.0. Microsoft also publishes checksums which should be used to verify the downloaded file.

**Comment by frostworx** [comment]
Yeah I've seen 6.0.9 exists, but seems like 6.0.6 is currently used by Vortex (first attempt is to get the url directly from the app.asar file, my 6.0.6 is the hardcoded 2nd choice)

**Comment by frostworx** [comment]
In theory, Vortex should work just fine in the current state - reports would still be fine.

The only thing missing is the _(optional)_ automated activation of the autodetected games, which worked perfectly fine before,
by setting `settings.mods.activator` of the corresponding game to hardlink_activator automatically.

Apparently, this does [no longer work](https://github.com/frostworx/steamtinkerlaunch/issues/555#issuecomment-1238369606)
_(or better is no longer enough to actually activate the game)_

When activating a game from within Vortex directly, the following three configurations options are automatically added for the activated game _(besides settings.mods.activator)_:
```
settings.profiles.activeProfileId
settings.profiles.lastActiveProfile.$NEXUSGAMEID
settings.profiles.nextProfileId
```

All three have a random 9 chars long value.
No idea yet, if those options need to be set now as well to actually activate the game, but
the above commit introduces a _(wip)_ command line option to activate a game within Vortex,
which also tries to set those options to a random string.
It does not work yet for still unknown reasons, but might help to further debug this.
_(example: `steamtinkerlaunch vortex activate 996580`)_

_(Vortex is a bit with confused/confusing with using quoted configuration options, still possible that this might cause new problems as well)_

**Comment by frostworx** [comment]
ah, probably the `NEXUSGAMEID` directory in 
`~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Roaming/Vortex/`
might need some autogenerated files as well to activate the self-rolled random string above.

```
./snapshots
./snapshots/snapshot.json
./profiles
./profiles/rkrOqInbs
```

maybe next week... 👋

edit: nope, seems like the ldb binary blobs in state.v2 are the problem. like not fixable, if Vortex doesn't offer a command line option to activate a game

**Comment by ghost** [comment]
> ah, probably the `NEXUSGAMEID` directory in `~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Roaming/Vortex/` might need some autogenerated files as well to activate the self-rolled random string above.
> 
> ```
> ./snapshots
> ./snapshots/snapshot.json
> ./profiles
> ./profiles/rkrOqInbs
> ```
> 
> maybe next week... wave
> 
> edit: nope, seems like the ldb binary blobs in state.v2 are the problem. like not fixable, if Vortex doesn't offer a command line option to activate a game

Vortex already has a helper library which detects where Steam games are located. It will do so when given a valid Steam Library to read from. My installer copies the user's actual Steam Library configuration into the Vortex prefix and replaces the unix paths to each library's location with the generic C: Steam Library location. Then, by linking all real game locations to their respective location in that generic Steam Library, Vortex extensions can automatically detect Steam games without issue. The only downside to this approach is needing to update the symlinks when new games are added or installed games are moved in the native Steam library. Everything else game detection related can be solved within Vortex normally, like setting your own download and staging folders (although the option to have that process automated by your script is neat).

TLDR: Vortex is already looking for the games. Your strategy seems to be fighting with the command line interface, rather than leveraging the detection measures Vortex and its extension authors have already implemented to correctly identify games. So work with Vortex, not against it?

**Comment by frostworx** [comment]
not helpful in any way

**Comment by frostworx** [comment]
@ "😕" - Why not work with steamtinkerlaunch, not against it? 🤨

**Comment by ghost** [comment]
> @ "confused" - Why not work with steamtinkerlaunch, not against it? raised_eyebrow

Don't get me wrong, I do think it would be nice to be able to activate a game in the way you are describing. However, as an end user, I can already activate a game which has been detected by Vortex in 1 click on the game list view. Your implementation seems like over-engineering a script to edit Vortex via a fully featured CLI. I wrote my script in bash, so you could easily copy paste any portion of it directly to STL. I would like to see my strategy implemented instead, but I wasn't holding my breath for another contributor to or jumping to make those changes myself since I expected this response and I'm more interested in porting the app directly to Linux. My script not having a proper GUI to launch the symlinker, but already having a simple function call for it, I think, makes it a good fit for STL, but
> not helpful in any way

is a quick way to turn down a suggestion. :shrug:

**Comment by frostworx** [comment]
Sorry, some of your replies seem to simply want to advertise your scripts for me and not actually help. Likely a misunderstanding from my side, so apologies for that.

No offense, but no - I won't copy paste anything from your script. I'd say the style doesn't match...
I also haven't looked through your scripts in detail, but pretty much everything seems very limited and hardcoded and therefore adopting the code is no option as well (couldn't find your "strategy", but only read a few seconds in it).

Vortex offers exactly those command line parameters which are required to automatically activate all compatible installed games automatically. This worked excellent for a long time and apparently no longer does. So who works against whom?
You might have missed that steamtinkerlaunch already does tons of automatic symlinking and I see absolutely no reason why I should spend even more time into more functions to work around the broken feature.
I do not even use Vortex (or MO2). Would be nice for modders for sure when you succeed with your attempts. Good luck and much fun with it any way.
Would make sense to freeze this "issue" until you're done, and then wait if someone is interested in adding a PR for your fork.
*shrug*

**Comment by frostworx** [comment]
> In theory, Vortex should work just fine in the current state - reports would still be fine.
> 
> The only thing missing is the _(optional)_ automated activation of the autodetected games, which worked perfectly fine before,

I haven't touched Vortex since. Does anybody want to confirm or reject this?

**Comment by sonic2kk** [comment]
I haven't gotten around to testing yet but several users have reported issues with setting up "staging folders" and deploying mods with Vortex. I don't use Vortex so I'm not sure what this means but if anyone could look into this specifically that would be awesome - This seems to be the main problem people are having lately with their Vortex games and STL (and maybe in general with Vortex).

It seems like staging folders in `z:\` paths are causing issues when users try to deploy mods. It seems like Vortex complains about permissions and not being able to write to a folder on a `z:\` drive path, like `z:\home\user\mods` or whatever. If someone with experience modding games with Vortex could test and see what works, what doesn't and if applicable how to fix issues, as well as attaching any relevant log files (I think Vortex has specific logs but I'm not sure where?) it would be really helpful in figuring out the status of Vortex at the moment!

Even though I don't use Vortex I own several games compatible with it, so if there are any fairly straightforward steps to reproduce - and hopefully subsequently _resolve_ - issues I can help try to verify this. Given my inexpensive with Vortex it's very possible that I could end up diving into using it and messing something up completely unrelated to STL, so reports from users that know what they're doing with Vortex are more than welcome to submit reports!

**Comment by frostworx** [comment]
Thanks for the summary. Indeed several people claim that the staging folders are broken.
Whenever I test this, they still work for me, so we need additional information, apparently.

steps to reproduce from scratch _(please ask if something is unclear)_

- start with a clean `~/.config/steamtinkerlaunch` and `/dev/shm/steamtinkerlaunch` directory
- run `steamtinkerlaunch vortex start` _(steam doesn't need to be running)_
- **wait** (this requires several minutes, depending on the amount of installed vortex compatible games). If inpatient, check the logs while it is running _(`/dev/shm/steamtinkerlaunch`)_
- when it is done, Vortex will open
_(just noticed that the `windowsdesktop-runtime-6.0.6-win-x64.exe` cut from the vortex _(1.6.14)_ 'resources/app.asar' was removed by M$ upstream, so automatic download doesn't work currently (seems like nobody tested that as well).Just a minor annoyance and irrelevant, you can still click the fix button in Vortex for now)_
- before you do anything in Vortex, you can already check the file `~/.config/steamtinkerlaunch/vortex/stages.txt`.
Here are all used staging folders - each for every partition/mount point used in your Steam Library Paths you defined in Steam. This is important, because we need to use "hardlinks" under Linux (means the mods/staging folders need to be on the same partition as the game itself). In `/dev/shm/steamtinkerlaunch/vortset.cmd` _(this cmd was created and already run during the install procedure above)_ you can see that a `mods.installPath` is configured per game. This is the auto-configured staging folder used for the game - for me this is always correct without any user interaction required.
- now "Manage" an installed game from the menu in Vortex _(this step was not required before, all autodetected games were automatically set to managed previously - maybe worth to fix any time later, but serious help welcome of course)_
- when the game is "managed", click Settings → Mods, and you'll see that the `mods.installPath` autoconfigured above is defined here as staging folder using Hardlink Deployment

If something does not work as expected during above steps, you're invited to report with brand new log _(created during the steps above)_ steamtinkerlaunch.log installDotNet.log, vortset.cmd might be interesting _(YMMV)_

I haven't tested any further usage while writing this, but for the beginning it is enough to know if the above steps cause any trouble for anybody. If Vortex behaves unusual from here, this is a separate issue _(which can be hopefully fixes from our side one day)_

Happy testing


edit: as mentioned above, the `windowsdesktop-runtime` download urls built into Vortex seem to be fragile, so in theory it would be the best implementation to try that download first _(to make sure the same tested version is used in the first place)_
and if it fails, pick the correct version from https://github.com/dotnet/core/tree/main/release-notes/6.0 and extract the up to date url and check sum from the corresponding subdirectory md _(similar as @NicBOMB suggested earlier)_
I won't jump through the hoops and implement anything which uses this weird fragile structure though _("yeah sure we bought github, but we do not provide sane downloads anyway for our own stuff")_
If nobody wants to PR this, I guess the easiest solution would be to add user-configurable download urls and checksums
_(or better Vortex provides working download urls somewhere)_

**Comment by sonic2kk** [comment]
Ah! Thank you! I will test this as soon as I have time but, I wonder if the problem stems from users wanting to change the staging folder? It seems like users want to change this folder to something else from the reports that I have seen. That would explain why it doesn't work. And in fact I could see why a user would want to do that, many times mods are stored on other drives because their game drives might be too small to store mods. But of course there's nothing STL can do about this - If you're using Vortex regularly you would need to do this (when I tested it out years ago with Lutris, you needed to install your Vortex instance onto the same drive as your games)

I wonder if symlinking mods to that staging folder would work? Probably not if we need to use Vortex hardlinking on Linux.

Interesting though, the steps seem clear enough to follow so once I have time to download a few mods for a chosen game I'll give it a shot!

**Comment by frostworx** [comment]
the staging folder needs to be on the same physical partition as the game. it is used for the active mods, not for the downloaded ones. iirc you can also change the staging folder, but I'm sure many users would do it wrong (and actually already do).

edit: as always very nice of you that you test, but it would be nice to see some vortex users help as well.

**Comment by Arcitec** [comment]
Hi again, the thing that ~~complicates~~ makes totally fucking impossible (🤣) all testing for me is that I use Steam Flatpak, and the Flathub SteamTinkerLaunch is outdated because it uses tagged releases (not git-master). I cannot test new patches that I do not have access to, sorry. :/

I am on SteamTinkerLaunch 11.11, which by the way is unable to download GE-Proton as you know. I am starting to wonder if the Flathub version of STL should move to being built from Git-master instead. Here you can see how outdated it is:

https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/blob/master/com.valvesoftware.Steam.Utility.steamtinkerlaunch.yml#L50

Furthermore, I can at least report that the Vortex "Hardlink Deployment" choice has come back in the Vortex GUI, so it's not removed, which is good news.

**Comment by Arcitec** [comment]
I compiled a flatpak version of the latest git commit for STL...

So far I am trying to install a Skyrim mod collection. I noticed 1 problem so far: Vortex isn't running with proper Locale I guess?

![locale-error](https://user-images.githubusercontent.com/38923130/194765644-7dc5e86a-d2f5-4387-aa8e-4ed990674694.jpg)

I opened the archive manually to check what the filename really is and I see that it's like this:

![actual-file](https://user-images.githubusercontent.com/38923130/194765693-ff5934b7-bb2b-4c88-8947-02fe1cc03247.jpg)

Edit: It's the 8.4.2 pack from https://www.nexusmods.com/skyrimspecialedition/mods/2347?tab=files, I am gonna keep investigating...

**I suspect that this file is misnamed by the mod author, but at the same time I suspect that STL can start Vortex with some proper Locale info to make Vortex able to find that file.**

**Comment by Arcitec** [comment]
The other issue I discovered is that if you get a notification about mod conflicts, and click resolve, you get the UI for resolving order. I then clicked the "???" field to mark it as "load after (suggested)". This made Vortex completely freeze. I had to force kill it after a few minutes of waiting.

![freeze](https://user-images.githubusercontent.com/38923130/194766102-1c3f9860-c6e6-4797-9ff5-58cc7ee13556.jpg)

**Comment by frostworx** [comment]
thanks for testing. for flatpak related issues please use the [flatpak issue](https://github.com/frostworx/steamtinkerlaunch/issues/27). can't help with that. Currently it is not unlikely that your screenshot issues are either flatpak and/or proton related, because I see nothing which would point to a steamtinkerlaunch issue at the moment.

**Comment by ghost** [comment]
> The other issue I discovered is that if you get a notification about mod conflicts, and click resolve, you get the UI for resolving order. I then clicked the "???" field to mark it as "load after (suggested)". This made Vortex completely freeze. I had to force kill it after a few minutes of waiting.
> 
> ![freeze](https://user-images.githubusercontent.com/38923130/194766102-1c3f9860-c6e6-4797-9ff5-58cc7ee13556.jpg)

I encountered this as well, though not on the STL flatpak. I did not need to kill the window. Simply minimizing and maximizing a few times seemed to refresh the window. Your results may vary.

**Comment by Arcitec** [comment]
@frostworx Yeah the crash is probably Wine-related, but the Locale (filename language interpretation) issue is probably STL related. Starting Vortex with some Wine flag to set the language/filename interpretation is probably gonna fix that.

**Comment by frostworx** [comment]
> @frostworx Yeah the crash is probably Wine-related, but the Locale (filename language interpretation) issue is probably STL related. Starting Vortex with some Wine flag to set the language/filename interpretation is probably gonna fix that.

then adding `restoreOrgVars` before the vortex launch should work, which sets `LC_ALL` to system default.
edit: assuming flatpak doesn't do something additionally here, of course

**Comment by Arcitec** [comment]
> I encountered this as well, though not on the STL flatpak. I did not need to kill the window. Simply minimizing and maximizing a few times seemed to refresh the window. Your results may vary.

Thanks, will try that next time it hangs. I just successfully used that window this time without it hanging.

> then adding restoreOrgVars before the vortex launch should work, which sets LC_ALL to system default.
> edit: assuming flatpak doesn't do something additionally here, of course

Yeah setting `LC_ALL` sounds correct. But I can't build the Flatpak with that change so I cannot test it. Was hard enough to make a flatpak build from a specific git commit. It downloads the source code from GitHub every time it generates the flatpak, so I can't change things.

Anyway I have now deployed to Skyrim, things generally worked pretty okay. List of issues:

- The locale filename issue.
- Hanging in the conflict resolution window (not related to STL, workaround seems to be to minimize and maximize vortex).
- No integration with web browser "nxm://" links so Vortex installation is a bit complex, but I solve it by going to "Vortex: Downloads:" in the app and starting downloads that way. And I bought Vortex premium for 1 month to avoid having to painfully download mods externally outside vortex app. With premium they download inside the app itself and it works well.

**Comment by frostworx** [comment]
There is a nxm protocol implementation, which worked last time I tried.
I'm currently working on a [mo2 overhaul](https://github.com/frostworx/steamtinkerlaunch/issues/598#issuecomment-1272503295), including a better nxm handler (which already works). I'll check if vortex can be improved as well.
still can be a flatpak issue, a log might help to find out...

**Comment by ghost** [comment]
> There is a nxm protocol implementation, which worked last time I tried. I'm currently working on a [mo2 overhaul](https://github.com/frostworx/steamtinkerlaunch/issues/598#issuecomment-1272503295), including a better nxm handler (which already works). I'll check if vortex can be improved as well. still can be a flatpak issue, a log might help to find out...

I have made an nxm handler for Vortex when running in native WINE or Lutris flatpak'd.
Below I've stripped any old references and mostly adapted it for STL's commands:

```bash
#!/usr/bin/bash
DESKTOP_FNAME="vortex-downloads-handler.desktop";
DESKTOP_APPLS=~/.local/share/applications/;
DESKTOP_FPATH="$DESKTOP_APPLS$DESKTOP_FNAME";
if [ "$STL_VERSION" == "flatpak" ]; then
    WRAPPER_CMD="flatpak run com.valvesoftware.Steam.Utility.steamtinkerlaunch";
else
    WRAPPER_CMD="steamtinkerlaunch";
fi;
printf "%s\n" "INFO: Updating nxm link handling for Vortex!";
printf "%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n\n" \
"[Desktop Entry]" \
"Categories=Game;Network;" \
"Comment[en_US]=NXM Protocol Download Handler" \
"Comment=NXM Protocol Download Handler" \
"Exec=$WRAPPER_CMD vortex url %u" \
"Icon=lutris_vortex-mod-manager" \
"MimeType=x-scheme-handler/nxm;x-scheme-handler/nxm-protocol;" \
"Name[en_US]=Vortex" \
"Name=Vortex" \
"NoDisplay=true" \
"StartupNotify=true" \
"Terminal=false" \
"Type=Application" \
> "$DESKTOP_FPATH";

xdg-mime default "$DESKTOP_FPATH" x-scheme-handler/nxm x-scheme-handler/nxm-protocol;
fix_mimetypes(){
    if [ -f "$1" ]; then
        printf "%s\n" "INFO: Fixing mimetype association of nxm: links in \"$1\"";
        sed -E -i "s/x-scheme-handler\/nxm=[^[=$=]]\+/x-scheme-handler\/nxm=$DESKTOP_FNAME;/" "$1";
        check="$(grep -a -o -e "x-scheme-handler/nxm=$DESKTOP_FNAME;" "$1")";
        if [ -z "$check" ]; then
            printf "%s\n" "x-scheme-handler/nxm=$DESKTOP_FNAME;" >> "$1";
        fi;
        sed -E -i "s/x-scheme-handler\/nxm-protocol=[^[=$=]]\+/x-scheme-handler\/nxm-protocol=$DESKTOP_FNAME;/" "$1";
        check="$(grep -a -o -e "x-scheme-handler/nxm-protocol=$DESKTOP_FNAME;" "$1")"
        if [ -z "$check" ]; then
            printf "%s\n" "x-scheme-handler/nxm-protocol=$DESKTOP_FNAME;" >> "$1";
        fi;
    else
        printf "%s\n%s\n%s\n\n" "$2" "x-scheme-handler/nxm=$DESKTOP_FNAME;" "x-scheme-handler/nxm-protocol=$DESKTOP_FNAME;" > "$1";
    fi;
};
fix_mimetypes "$DESKTOP_APPLS"mimeinfo.cache "[MIME Cache]";
fix_mimetypes "$DESKTOP_APPLS"defaults.list "[Default Applications]";

printf "%s\n" "DONE: Made a desktop entry for Vortex at \"$DESKTOP_FPATH\"";

```
The mimetype changing commands may be unnecessary and/or inaccessible via flatpak, it's just how I assisted the native Lutris users in getting the correct URL handling automatically. You'll need to use the approriate flatpak command for handling mimetypes or include an actual `.desktop` file specifically for handling that protocol in the flatpak release. Hope this helps, though it sounds like you've already got things working for mo2, so this should be a simple change.

**Comment by frostworx** [comment]
thanks for trying to help @NicBOMB!
Your script doesn't look very different from my old/current implementation though:
https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L12084

The part I improved on MO2 side, was not the desktop file itself, but that where the used proton and compatdata are determined.
I just checked if it needs to be improved for Vortex as well, and I am not convinced that any changes are required _(currently)_
_(iirc the flatpak part was already resolved before, correct me if I'm wrong, flatpak users :))_

**Comment by Arcitec** [comment]
I dunno, I disabled and enabled the "handle Vortex Mod Manager links" option in the Vortex settings but the Flatpak still doesn't listen to the links. Other than that and the issue with locale filename, things are running fine. :)

**Comment by frostworx** [comment]
> still can be a flatpak issue, a log might help to find out...

**Comment by BottomNotch** [comment]
I apologize if this is redundant (this is a really long thread to be able to read through everything) but I have some information that might be useful.   I've been trying to get nxm link handling working with vortex all day and finally got it working.  I installed STL with ProtonUp-QT, ran Fallout 4 with STL and installed vortex with STL.  After launching vortex I got that message about dotnet6 being missing, clicked the fix button and it installed dotnet6.  After this it still wouldn't work on the flatpak version of Firefox, but it did work once I installed Firefox with pacman.  This was all on my steam deck if that makes a difference.

**Comment by BottomNotch** [comment]
Also, I'm not sure if this applies to systems other than the steam deck, but this is a fix that's supposed to help with this sort of issue with flatpak browsers, though it didn't help me.
https://www.reddit.com/r/SteamDeck/comments/xbuv7a/comment/iov5y0o/

**Comment by BottomNotch** [comment]
Also, a work around to install collections with flatpak Firefox (since they can't be installed manually) is to right click the "add to vortex" button, copy the URL, then run `SteamTinkerLauncher vortex u <collection url>`

**Comment by Sparkwave2** [comment]
I know this is unrelated to steamtinkerlaunch or steam deck, but trying to install Vortex on KDE Neon, and the above method didn't work

**Comment by ghost** [comment]
> above method didn't work

Which? Vortex from STL flatpak? Vortex from STL Native?

> still can be a flatpak issue, a log might help to find out...

**Comment by frostworx** [comment]
whoops, totally forgot to check your comments, @BottomNotch! Sorry for that!
~~It is almost bedtime now here, but writing a note to myself, so I won't forget it again...~~

edit: replying now 😀
hmm, I recently noticed that urls within wine are no longer forwarded to my native browser _(which just worked before)_.
I did not really investigate this, but your `xdg-desktop-portal` url might be a good hint here, because I recently pulled it into my system together with flatpak. time to check this shortly. Thanks for your help!

edit: I can confirm that it works again after having removed xdg-desktop-portal(-gtk) and flatpak from my system.

**Comment by BottomNotch** [comment]
> whoops, totally forgot to check your comments, @BottomNotch! Sorry for that! ~It is almost bedtime now here, but writing a note to myself, so I won't forget it again...~
> 
> edit: replying now 😀 hmm, I recently noticed that urls within wine are no longer forwarded to my native browser _(which just worked before)_. I did not really investigate this, but your `xdg-desktop-portal` url might be a good hint here, because I recently pulled it into my system together with flatpak. time to check this shortly. Thanks for your help!

No problem! And now I'm doing something a little crazier.  The steam deck repos have an old version of Firefox, so I installed an up to date version in a distrobox, added `distrobox-host-exec` right after `Exec=` in vortex-steamtinkerlaunch-dl.desktop, and now the vortex download button works from a browser running inside a containerized environment.  I hope this is helpful to any steam deck users who want to get this working with an up to date version of Firefox.

**Comment by sonic2kk** [comment]
Steam Deck should already package an up-to-date version of Firefox Flatpak, I thought regular Firefox was removed a while ago. Maybe that's only in the Beta...

Good to know though 😃

**Comment by BottomNotch** [comment]
> Steam Deck should already package an up-to-date version of Firefox Flatpak, I thought regular Firefox was removed a while ago. Maybe that's only in the Beta...
> 
> Good to know though 😃

But nxm handling isn't working with the flatpak version.

**Comment by frostworx** [comment]
> a log might help to find out...

**Comment by Arcitec** [comment]
I have figured out something that is really fundamentally broken about how Vortex is setup. I read through other tickets and realize you are aware of this issue too.

**The issue: Vortex runs on its own Windows installation, separate from the game, which means Vortex can't properly write user-data/per-user config files for the game container.**

So as a result, all Skyrim mod "load instructions" are stored inside the Vortex installation:

```
~/.var/app/com.valvesoftware.Steam/config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Skyrim Special Edition
```

And the actual Skyrim game compatdata doesn't have that folder/data at all, so the mods aren't loading properly.

Skyrim uses these two files in that folder:

```
plugins.txt = which plugins to load
loadorder.txt = which order to load them
```

This is a core problem in how Vortex is managed/running. I wonder what the solutions are? Just telling people to manually copy the text files to their Skyrim game container perhaps. That's how I solve it.

I can't imagine any universal solutions. STL obviously needs to keep Vortex inside its own container, so that Vortex itself runs properly. But it does mean that users have to manually be aware of this and copy the finished config files into the game container.

Something else to keep in mind: Symlinks MIGHT work too, but in my case (Flatpak Steam) it probably means that I have to mess with Flatseal permissions to ensure that the symlink target is accessible from the sandbox.

PS: I didn't notice this because all texture/data mods work. The thing that's broken is all plugin-based mods. Lucky for me I just played like 6 hours so far, so I can restart the game properly with mods enabled without too much sadness. I'll even take the opportunity to add a few more mods that will make the game more enjoyable. :)

**Comment by Arcitec** [comment]
I have a Flatpak solution. It can work natively but will need different file paths.

# For Skyrim on Flatpak, I have these two commands as a solution:

Option 1: Best, if it works. This sets up symlinks.which means that it only has to be done once and automatically stays in sync with your Vortex config, but it MAY not work in case your Wine cannot read/follow the symlinks (it worked for me):

```sh
for f in loadorder.txt plugins.txt; do ln -s ~/.var/app/com.valvesoftware.Steam/config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/"Skyrim Special Edition"/"$f" ~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/AppData/Local/"Skyrim Special Edition"/"$f"; done
```

Option 2: A manual copy, which always work but must be manually repeated every time you change anything about the mods in Vortex:

```sh
for f in loadorder.txt plugins.txt; do cp -f ~/.var/app/com.valvesoftware.Steam/config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/"Skyrim Special Edition"/"$f" ~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/AppData/Local/"Skyrim Special Edition"/"$f"; done
```

**Comment by frostworx** [comment]
steamtinklerlaunch already sets all required symlinks. This already works without any problems for a very long time.
If it does no longer work please provide logs...

**Comment by SentaiBrad** [comment]
I'm unsure if this thread is being looked at by anyone interested in maintaining the Vortex portion, but linking #637 here just in case.

**Comment by sonic2kk** [comment]
Aside from NXM links, can anyone give an update on the status of this? How does Vortex modding work through SteamTinkerLaunch? I get the impression from reading the issues and looking at usage that it works but has a couple of hiccups with the NXM link handlers and some hiccups on Flatpak.

**Comment by BottomNotch** [comment]
> Aside from NXM links, can anyone give an update on the status of this? How does Vortex modding work through SteamTinkerLaunch? I get the impression from reading the issues and looking at usage that it works but has a couple of hiccups with the NXM link handlers and some hiccups on Flatpak.

One annoyance was whenever I changed the mod download folder, it would revert next time I open Vortex, I ended up just making a symlink to where I wanted the downloads to actually go.
Also, it stops responding every once in awhile, and sometimes it would start working again, sometimes I had to kill it and restart it. I also had some issues with resizing the window (the bottom would be slightly cut off when maximized, and a few other things that I don't remember exactly off the top of my head); but I'm guessing those last two are more wine issue than STL issues.  It's been a couple of weeks since I last used it so there might be some other small things I'm forgetting, but overall it's a good experience.

I also just remembered I was having trouble getting it to work with a non-steam game (GOG Skyrim: AE) but that very well may be an ID10T problem on my end. I didn't need collections for that game so I just switched to MO2.

**Comment by sonic2kk** [comment]
> One annoyance was whenever I changed the mod download folder, it would revert next time I open Vortex, I ended up just making a symlink to where I wanted the downloads to actually go.

Hmm, there's a chance this could be a Vortex bug but likely this is some kind of configuration thing. Maybe Vortex can't see the mod folder on startup for some reason so it reverts to a default.

> Also, it stops responding every once in awhile, and sometimes it would start working again, sometimes I had to kill it and restart it. I also had some issues with resizing the window (the bottom would be slightly cut off when maximized, and a few other things that I don't remember exactly off the top of my head); but I'm guessing those last two are more wine issue than STL issues

Probably Vortex issues instead of Wine issues imo but yup I would agree with you that this isn't a SteamTinkerLaunch problem.

> but overall it's a good experience

Great to hear! Thank you!

> I also just remembered I was having trouble getting it to work with a non-steam game (GOG Skyrim: AE) 

Hmm that's interesting but it could be an issue with however STL detects games. I'm personally not interested in supporting modding Non-Steam Games with Vortex/MO2 via STL but if it's a relatively straightforward fix someone could open a PR for it :-)

<hr>

Okay, so there are a couple of what I understand to be minor UI bugs and freezing (not an STL problem afaik but if there's a Winetrick to fix it we can install that when we install Vortex), the Downloads folder keeps reverting on launch and the NXM link handler is broken.

For the Downloads folder reverting, I wonder if STL could automatically set up a symlink like you did. Not sure how we'd do this, maybe in the global menu/game menu we could set a downloads directory and create a symlink that way.

The NXM link thing is becoming a problem. There was a script linked earlier, I wonder if someone who understands the process more could contribute a PR to implement better mime type integration for Vortex? :-)

It's worth noting that MO2 seems to have mime type troubles sometimes (on Steam Deck only going by the reports), and that might be fixed in the mo2-overhaul branch.

The Downloads directory thing is something I really want to look into. I think that might be a nice usability fix. I'll keep that on my radar.

Thank you a ton for the feedback @BottomNotch, it's very much appreciated. Just to I guess confirm my suspicions, but DotNet6 shouldn't be a problem anymore right?

**Comment by BottomNotch** [comment]
> > One annoyance was whenever I changed the mod download folder, it would revert next time I open Vortex, I ended up just making a symlink to where I wanted the downloads to actually go.
> 
> Hmm, there's a chance this could be a Vortex bug but likely this is some kind of configuration thing. Maybe Vortex can't see the mod folder on startup for some reason so it reverts to a default.
> 
> > Also, it stops responding every once in awhile, and sometimes it would start working again, sometimes I had to kill it and restart it. I also had some issues with resizing the window (the bottom would be slightly cut off when maximized, and a few other things that I don't remember exactly off the top of my head); but I'm guessing those last two are more wine issue than STL issues
> 
> Probably Vortex issues instead of Wine issues imo but yup I would agree with you that this isn't a SteamTinkerLaunch problem.
> 
> > but overall it's a good experience
> 
> Great to hear! Thank you!
> 
> > I also just remembered I was having trouble getting it to work with a non-steam game (GOG Skyrim: AE)
> 
> Hmm that's interesting but it could be an issue with however STL detects games. I'm personally not interested in supporting modding Non-Steam Games with Vortex/MO2 via STL but if it's a relatively straightforward fix someone could open a PR for it :-)
> 
> Okay, so there are a couple of what I understand to be minor UI bugs and freezing (not an STL problem afaik but if there's a Winetrick to fix it we can install that when we install Vortex), the Downloads folder keeps reverting on launch and the NXM link handler is broken.
> 
> For the Downloads folder reverting, I wonder if STL could automatically set up a symlink like you did. Not sure how we'd do this, maybe in the global menu/game menu we could set a downloads directory and create a symlink that way.
> 
> The NXM link thing is becoming a problem. There was a script linked earlier, I wonder if someone who understands the process more could contribute a PR to implement better mime type integration for Vortex? :-)
> 
> It's worth noting that MO2 seems to have mime type troubles sometimes (on Steam Deck only going by the reports), and that might be fixed in the mo2-overhaul branch.
> 
> The Downloads directory thing is something I really want to look into. I think that might be a nice usability fix. I'll keep that on my radar.
> 
> Thank you a ton for the feedback @BottomNotch, it's very much appreciated. Just to I guess confirm my suspicions, but DotNet6 shouldn't be a problem anymore right?

No problem, happy to help.  The steam deck mime type woes I think are more flatpak related than steam deck related; but since flatpaks are the easiest way to install software on the deck, that's where a lot of the issue are coming up. This is just speculation though.

As for dotnet6, I never had any issues, so I'm not sure if it's resolved for anyone who was having trouble, or what might have been different about their configuration.

Also, I said wine issue because I never had those issues with when modding games with Vortex on windows, but I suppose that's not really relevant, because either way, it's not STL causing the issue.

Something else that may be relevant to the Downloads folder issue: I was changing it from my internal storage to my SD card, maybe it being on a different storage device was making vortex unhappy (though I didn't have issues changing the mod staging folder to the SD card).

**Comment by sonic2kk** [comment]
> The steam deck mime type woes I think are more flatpak related than steam deck related; but since flatpaks are the easiest way to install software on the deck, that's where a lot of the issue are coming up. This is just speculation though.

The only Flatpak in the equation on Steam Deck is Firefox Flatpak. STL Flatpak is unsupported on Steam Deck and Steam does not come as a Flatpak. But if you were referring to Firefox Flatpak you could be right.

I tested MO2 a while ago on my laptop with Firefox Flatpak and it did work but it also sounds like MO2 worked for you, so this could just be a Vortex thing (may need to look into updating how to the .desktop file is created).

<hr>

Interesting hint about the SD card thing. There were notes before I think around the web about the SD card on Steam Deck specifically and Wine having some "fun" behaviour - I think the RE4HD Steam Deck instructions mentioned something about having to set a variable. Not sure myself, the comments seemed to suggest it wasn't needed at least with Bottles, but maybe we need to set that option on Steam Deck if it isn't already. I'll look into that at some point too but if all else fails, adding an option in the global menu and per-game to create a Downloads folder symlink for mods is probably an acceptable workaround.

Awesome, the state of Vortex support is sounding a lot better than I thought! I realise you're just one user but still, it's nice to hear that it works and get some positive feedback. It sounds like there are just a couple of issues to fix, but it's not completely broken or even mostly broken 😃

**Comment by BottomNotch** [comment]
> > The steam deck mime type woes I think are more flatpak related than steam deck related; but since flatpaks are the easiest way to install software on the deck, that's where a lot of the issue are coming up. This is just speculation though.
> 
> The only Flatpak in the equation on Steam Deck is Firefox Flatpak. STL Flatpak is unsupported on Steam Deck and Steam does not come as a Flatpak. But if you were referring to Firefox Flatpak you could be right.
> 
> I tested MO2 a while ago on my laptop with Firefox Flatpak and it did work but it also sounds like MO2 worked for you, so this could just be a Vortex thing (may need to look into updating how to the .desktop file is created).
> 
> Interesting hint about the SD card thing. There were notes before I think around the web about the SD card on Steam Deck specifically and Wine having some "fun" behaviour - I think the RE4HD Steam Deck instructions mentioned something about having to set a variable. Not sure myself, the comments seemed to suggest it wasn't needed at least with Bottles, but maybe we need to set that option on Steam Deck if it isn't already. I'll look into that at some point too but if all else fails, adding an option in the global menu and per-game to create a Downloads folder symlink for mods is probably an acceptable workaround.
> 
> Awesome, the state of Vortex support is sounding a lot better than I thought! I realise you're just one user but still, it's nice to hear that it works and get some positive feedback. It sounds like there are just a couple of issues to fix, but it's not completely broken or even mostly broken 😃

Sorry, I should have been more specific, I did mean the Firefox flatpak, I installed STL through ProtonUp-QT.  I've actually moved away completely from using flatpak web browsers, I just use distrobox now for most software I use exclusively in desktop mode on my steam deck. Firefox installed in an Arch distrobox works great (though I had to modify the NXM handler script a bit so that it launches Vortex on the host system instead of trying launch it in the container).  I also should note that I never did have MO2 NXM link handling working, flatpak browser or otherwise (I'm not actually sure I tried with flatpak Firefox though).  I only wanted a small handful of mods for Skyrim, and I didn't feel like investigating the issue at the time, so I downloaded manually.

**Comment by Shadark** [comment]
Hi! I've posted this on my own issue #644 but it's already marked as offtopic in there because I realized that it's outside the scope of the original issue.

System: Steam Deck (SteamOS), STL manual installation (also with ProtonUp-Qt)

Currently I only have vanilla Skyrim + some mods installed with Vortex. I'm able to launch Skyrim Script Extender (SKSE) from the executable already configured in Vortex. So what I'm doing is:
- Launching Vortex by:
  - Launching Skyrim via STL and selecting Vortex OR
  - Directly from command line
- Selecting SKSE64 in the Tools section
- SKSE -> Skyrim opens with the mods I've installed/activated.

However, I'm not sure about the procedure to launch SKSE from "outside" Vortex but preserving the modlist. I've tried by activating Skyrim STL Vortex options, but as far as I see that only opens a GUI asking me if I want to load Vortex. If I don't do anything, SKSE -> Skyrim load, but without mods loaded. Also, vanilla Skryim being or not in the "Vortex" collection doesn't seem to do anything, either.

Just to confirm (in case this is a _bigger issue_ than the collection not working: are we supposed to get a Vortex modlist working from _outside_ Vortex? As in, opening Skyrim (without opening Vortex UI) and loading the preconfigured Vortex modpack. I thought yes, but I can't seem to get it working no matter what I configure in the Skyrim STL config.

Any insights about this? Thanks in advance!

**Comment by sonic2kk** [comment]
I just mentioned it in the other issue but posting here for completeness: To my understanding mods should only be loaded with your game when you run your game from Vortex Mod Manager (and same goes for MO2) - And this should be the case on Windows and Linux. At least to me, it would be *very* undesirable to have a game load with mods if you are not running it through a mod manager, and would make very little sense (how would you remember which mods you picked, set their load order, do other configuration etc?)

I don't use Vortex and I am not *overly* fond of it, so I am not sure what intended behaviour is. Someone that uses it, please chime in with what the expected behaviour is :+1:

**Comment by BottomNotch** [comment]
> I just mentioned it in the other issue but posting here for completeness: To my understanding mods should only be loaded with your game when you run your game from Vortex Mod Manager (and same goes for MO2) - And this should be the case on Windows and Linux. At least to me, it would be _very_ undesirable to have a game load with mods if you are not running it through a mod manager, and would make very little sense (how would you remember which mods you picked, set their load order, do other configuration etc?)
> 
> I don't use Vortex and I am not _overly_ fond of it, so I am not sure what intended behaviour is. Someone that uses it, please chime in with what the expected behaviour is 👍

The expected (or at least default) behavior for vortex is for enabled mods to be loaded no matter how the game is launched, and even if vortex is not running.  That's at least how it's always worked for me when I've used it on Windows, and that's how it's worked when I've used it through STL on my Steam Deck (except I was having issues with Skyrim, which I assumed was because it's a non-steam game).  Nexus Mod Manager works same way.  I'm also not so fond of Vortex, it's fine, but I much prefer MO2, I hope it gets support for Nexus Collections, though I don't personally have an issue with Vortex's mod deployment behavior.

**Comment by Shadark** [comment]
> I just mentioned it in the other issue but posting here for completeness: To my understanding mods should only be loaded with your game when you run your game from Vortex Mod Manager (and same goes for MO2) - And this should be the case on Windows and Linux. At least to me, it would be _very_ undesirable to have a game load with mods if you are not running it through a mod manager, and would make very little sense (how would you remember which mods you picked, set their load order, do other configuration etc?)
> 
> I don't use Vortex and I am not _overly_ fond of it, so I am not sure what intended behaviour is. Someone that uses it, please chime in with what the expected behaviour is 👍

Disclaimer: I'm not knowledgeable about how mod manager should work, but I thought, as @BottomNotch mentioned, that MO2 should load your configured modlist when you launch any executable through MO2, even if you don't directly open the MO2 UI, at least in Windows with something like ```"C:\My Programs\MO2\ModOrganizer.exe" "moshortcut://SkyrimSE:SKSE"``` you could launch your SKSE instance + mods directly.

With the knowledge about how Vortex works, I thought it could work out of the box by just managing the modlist/mod order for you and, since you're deploying the files to the Skyrim directory, you wouldn't need to open Vortex every time you want to launch your own modlist.

I can confirm that, indeed, I was able to apply Vortex modlist to my own Skyrim executable (Skyrim Together Reborn) by manually copying the files in ```/home/deck/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Application Data/Vortex/skyrimse/profiles/S1044rhNj/``` (plugins.txt and loadorder.txt) to ```/home/deck/.steam/steam/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/Local Settings/Application Data/Skyrim Special Edition/```. That way, my Skyrim setup (that was being launched by the STR executable) loaded the correct modlist and, since Vortex already deploys the mod files to the directory, everything seems to be working just fine.

But I'm guessing that this is outside of STL and it's just Vortex behavior? Anyway, at least I managed to _"fix"_ my STR issue by manually copying the files. Just a bit more tiresome to manage when I change some mods around.

**Comment by sonic2kk** [comment]
Thanks for all the background here, much appreciated! :+1: 

I just installed Vortex and actually got it loading, but there may be a problem where the global Vortex Proton version is not correctly set. I will look into that if possible.

There is also another issue I had where many games are not automatically discovered. I believe SteamTinkerLaunch manages autodiscoverable games by setting them in `misc/vortexgames.txt` - and this list is quite small. It will probably need expanded, and I will work on doing that soon if that is indeed the case.

I didn't try modding any games yet but it seems to work at least which is a lot better than I expected.

**Comment by frostworx** [comment]
`misc/vortexgames.txt` was "complete" at the time of writing _(in fact the whole vortex implementation once worked flawlessly)_. seems like multiple games were added _(/left beta)_ since.
Ideally such a helper file would not even be required.
It was always the idea that people using Vortex via steamtinkerlaunch contribute new additions to that list self motivated.
good luck!

edit: just launched it and multiple/most of the 228 supported games are still listed as "beta".
to "manage" beta supported games, vortex needs to download its extension - therefore the data for that game is not available before and apparently can't be seen by steamtinkerlaunch.

**Comment by sonic2kk** [comment]
> `misc/vortexgames.txt` was "complete" at the time of writing

Vortex sees to "add" games really fast - Sony's Sackboy game is listed as supported now, and Spider-Man Remastered had support very soon after launch too if I recall. The list of supported games is now close to 2,000, though I am not sure how many of those are games available on Steam and are "actually" supported.

> *(in fact the whole vortex implementation once worked flawlessly)*

I didn't test any mods but I just tested for another currently open issue (#647), and aside from one small fix to properly download dotnet6, Vortex installed without a hitch using GE-Proton7-38. The new issue opened yesterday may indicate that there are a couple of problems with detecting some game paths but I am not totally sure on that yet, it's still being investigated. There were no complaints about DotNet6.

I guess there are also some complaints about the mime-type handling *mainly* on Steam Deck and Flatpak, but that's a headache for me to look into another time :sweat:

<hr>

I actually looked into creating a helper script to generate a list of supported games, but ran into a couple of concerns:
1. Getting the AppID from the Steam API is gonna take a loooooooong time...
2. Some games return multiple AppIDs and manually checking each one would take a loooooooong time...
3. Game names might change overtime (e.g., the original Resident Evil 4 will probably be renamed to something like "Resident Evil 4 (2014)" when the RE4 Remake comes out in March) and dealing with that would be a pain...

Overall I just don't think it's worth it, and I will just manually add games/accept PRs that add games as and when that happens.

<hr>

> edit: just launched it and multiple/most of the 228 supported games are still listed as "beta".
to "manage" beta supported games, vortex needs to download its extension - therefore the data for that game is not available before and apparently can't be seen by steamtinkerlaunch.

This is interesting. Yakuza 0 needed me to download and run RyuModManager, but after doing that and after adding it to vortexgames.txt, STL was able to manage it properly.

I will be honest, I know very little about how Vortex works on Windows, how it works on Linux, and what potential problems there might currently be with it and STL. I am hoping this issue gives users that actually understand a bit more about how Vortex works a forum to discuss problems, hopefully also investigate problems and offer up potential fixes either for me to look into or in the form of PRs.

Support for a tool like Vortex is going to be really helped by contributors that have that understanding, so I am really hoping that someone can come along and help out if there are any major problems :-)

**Comment by sonic2kk** [comment]
I will probably close this issue closer to the next release. The initial issue was about DotNet6 breaking Vortex and that's now not an issue. And Vortex seems to work pretty well.

There's still the issue of the link handling and there's some Flatpak-specific tweaks needed, but we should probably get those moved to the Modding wiki.

There is some benefit in having an open ticket to track issues with Vortex (and potentially MO2 also) but I'm not sure anymore if it's better to have an open issue or just let people make bug reports ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by sonic2kk** [comment]
Hey @Bananaman, I don't have much context on the problem (and thus the meaning behind the solution) in the thread but if you would like and when you have the time, could you compile the steps to fix the problem you were facing into one single post? Then I could add the solution to the Modding wiki page :-)

**Comment by sonic2kk** [comment]
Going to close this issue, as there has been no updates here for a while now. The initial issue was related to dotnet6, but that seems to be resolved now :-)
