### ISSUE TITLE
not installing on steam deck

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#651]
## System Information
- SteamTinkerLaunch version: latest git
- Distribution: steamos stable
- Installation Method: download script/protonup

## Issue Description
On protonupqt it is not installing it just hangs and manually downloading and running the script gives this 
```
./steamtinkerlaunch 
Wed Nov  9 12:26:02 PM EST 2022 ERROR - loadLanguage - ###############################
Wed Nov  9 12:26:02 PM EST 2022 ERROR - loadLanguage - No language file could be loaded! For the initial setup at least one file (default english) is required
Wed Nov  9 12:26:02 PM EST 2022 ERROR - loadLanguage - You can ether copy a valid file to '/home/deck/.config/steamtinkerlaunch/lang' or '/home/deck/Applications/lang' or provide an absolute path via command line using the lang= option
Wed Nov  9 12:26:02 PM EST 2022 ERROR - loadLanguage - ###############################
```
Shouldn't it auto-download the langs and everything else into `/home/deck/stl/`?

## Logs
```
Wed Nov  9 12:31:26 PM EST 2022 INFO - setflatpak - started SteamTinkerLaunch from ./steamtinkerlaunch
Wed Nov  9 12:31:26 PM EST 2022 INFO - setLocalInstall - Looks like we have a non-root local install here - Updating paths...
Wed Nov  9 12:31:26 PM EST 2022 INFO - updateConfigEntry - Option 'GLOBALCOLLECTIONDIR' is updated with the new value '/home/deck/Applications/collections' in config 'global.conf'
Wed Nov  9 12:31:26 PM EST 2022 INFO - updateConfigEntry - Option 'GLOBALMISCDIR' is updated with the new value '/home/deck/Applications/misc' in config 'global.conf'
Wed Nov  9 12:31:26 PM EST 2022 INFO - updateConfigEntry - Option 'GLOBALSBSTWEAKS' is updated with the new value '/home/deck/Applications/sbstweaks' in config 'global.conf'
Wed Nov  9 12:31:27 PM EST 2022 INFO - updateConfigEntry - Option 'GLOBALTWEAKS' is updated with the new value '/home/deck/Applications/tweaks' in config 'global.conf'
Wed Nov  9 12:31:27 PM EST 2022 INFO - updateConfigEntry - Option 'GLOBALEVALDIR' is updated with the new value '/home/deck/Applications/eval' in config 'global.conf'
Wed Nov  9 12:31:27 PM EST 2022 INFO - updateConfigEntry - Option 'GLOBALSTLLANGDIR' is updated with the new value '/home/deck/Applications/lang' in config 'global.conf'
Wed Nov  9 12:31:27 PM EST 2022 INFO - updateConfigEntry - Option 'GLOBALSTLGUIDIR' is updated with the new value '/home/deck/Applications/guicfgs' in config 'global.conf'
Wed Nov  9 12:31:27 PM EST 2022 INFO - initAID - Set AID to PLACEHOLDERAID '31337'
Wed Nov  9 12:31:27 PM EST 2022 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Wed Nov  9 12:31:27 PM EST 2022 INFO - loadLangFile - Language from command line is 'english'
Wed Nov  9 12:31:27 PM EST 2022 INFO - loadLangFile - SYSTEMSTLCFGDIR is '/home/deck/Applications'
Wed Nov  9 12:31:27 PM EST 2022 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Wed Nov  9 12:31:27 PM EST 2022 ERROR - loadLangFile - Language file '/home/deck/Applications/lang//english.txt' could not be found
Wed Nov  9 12:31:27 PM EST 2022 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Wed Nov  9 12:31:27 PM EST 2022 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Wed Nov  9 12:31:27 PM EST 2022 ERROR - loadLanguage - ###############################
Wed Nov  9 12:31:27 PM EST 2022 ERROR - loadLanguage - No language file could be loaded! For the initial setup at least one file (default english) is required
Wed Nov  9 12:31:27 PM EST 2022 ERROR - loadLanguage - You can ether copy a valid file to '/home/deck/.config/steamtinkerlaunch/lang' or '/home/deck/Applications/lang' or provide an absolute path via command line using the lang= option
Wed Nov  9 12:31:27 PM EST 2022 ERROR - loadLanguage - ###############################
```

seems like the steam deck function is not running?

**Comment by sonic2kk** [comment]
Can you reproduce the ProtonUp-Qt hanging running ProtonUp-Qt from source? You may need to manually install the PUPQT dependencies. There were a couple of reports of hanging on install but I couldn't reproduce from source, so I think it may have been a Flatpak thing that has since been resolved in main.

Edit: Just seen the script itself is failing for you. I'll investigate now...

**Comment by sonic2kk** [comment]
Ooooh, the recent change in 60724837804b68fda6fbb08cb7ee04200ddab106 seem to be causing the issue. However it has a check for Steam Deck, I guess it's being called too early...

**Comment by sonic2kk** [comment]
Just pushed a commit which should hopefully resolve it. Config entry paths should get updated automatically too :-)

Not sure how I didn't catch this in my tests on Deck, but I did keep in mind for the last few days that this change could cause some issues. Thanks for reporting!

**Comment by zany130** [comment]
still seems to not call the steam deck function correctly...
```
./steamtinkerlaunch 
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLanguage - ###############################
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLanguage - No language file could be loaded! For the initial setup at least one file (default english) is required
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLanguage - You can ether copy a valid file to '/home/deck/.config/steamtinkerlaunch/lang' or '/usr/share/steamtinkerlaunch/lang' or provide an absolute path via command line using the lang= option
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLanguage - ###############################
(deck@steamdeck Applications)$ cat /dev/shm/steamtinkerlaunch/
menutemp/              prelog.log             steamtinkerlaunch.log  version                
(deck@steamdeck Applications)$ cat /dev/shm/steamtinkerlaunch/steamtinkerlaunch.log
Wed Nov  9 12:56:30 PM EST 2022 INFO - setflatpak - started SteamTinkerLaunch from ./steamtinkerlaunch
Wed Nov  9 12:56:30 PM EST 2022 INFO - initAID - Set AID to PLACEHOLDERAID '31337'
Wed Nov  9 12:56:30 PM EST 2022 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Wed Nov  9 12:56:30 PM EST 2022 INFO - loadLangFile - Language from command line is 'english'
Wed Nov  9 12:56:30 PM EST 2022 INFO - loadLangFile - SYSTEMSTLCFGDIR is '/usr/share/steamtinkerlaunch'
Wed Nov  9 12:56:30 PM EST 2022 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLangFile - Language file '/usr/share/steamtinkerlaunch/lang//english.txt' could not be found
Wed Nov  9 12:56:30 PM EST 2022 WARN - updateEditor - 'xdg-open' selected as editor or configured editor not found - trying to find an installed editor installed
Wed Nov  9 12:56:30 PM EST 2022 INFO - updateEditor - changing STLEDITOR to '/usr/bin/kwrite' in '/home/deck/.config/steamtinkerlaunch/global.conf'
Wed Nov  9 12:56:30 PM EST 2022 INFO - updateConfigEntry - Option 'STLEDITOR' is updated with the new value '/usr/bin/kwrite' in config 'global.conf'
Wed Nov  9 12:56:30 PM EST 2022 INFO - loadCfg - '/home/deck/.config/steamtinkerlaunch/global.conf' START
Wed Nov  9 12:56:30 PM EST 2022 INFO - loadCfg - '/home/deck/.config/steamtinkerlaunch/global.conf' STOP
Wed Nov  9 12:56:30 PM EST 2022 UPDATE - saveCfg - Replacing '/home/deck/.config/steamtinkerlaunch' with 'STLCFGDIR' in '/home/deck/.config/steamtinkerlaunch/global.conf'
Wed Nov  9 12:56:30 PM EST 2022 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Wed Nov  9 12:56:30 PM EST 2022 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLanguage - ###############################
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLanguage - No language file could be loaded! For the initial setup at least one file (default english) is required
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLanguage - You can ether copy a valid file to '/home/deck/.config/steamtinkerlaunch/lang' or '/usr/share/steamtinkerlaunch/lang' or provide an absolute path via command line using the lang= option
Wed Nov  9 12:56:30 PM EST 2022 ERROR - loadLanguage - ###############################

```

**Comment by sonic2kk** [comment]
Hmm, seems like it's unhappy about the language files for some reason. Could you try deleting/renaming your `global.conf`?

**Comment by sonic2kk** [comment]
Just thinking out loud but the local install check may need to go right after steamdedeckt...

**Comment by zany130** [comment]
that was with a clean `.config/steamtinkerlaunch` and /dev/shm/steamtinkerlaunch`

im thinking this may be faling 	```if [ -f "/etc/os-release" ] && grep -q "steamdeck" "/etc/os-release"; then		
		ONSTEAMDECK=1```
		
		
as this produces nothing (is it supposed to?)
```
(deck@steamdeck ~)$ grep -q "steamdeck" "/etc/os-release"
(deck@steamdeck ~)$ 
```

here is a cat 
```
cat /etc/os-release 
NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
HOME_URL="https://www.steampowered.com/"
DOCUMENTATION_URL="https://support.steampowered.com/"
SUPPORT_URL="https://support.steampowered.com/"
BUG_REPORT_URL="https://support.steampowered.com/"
LOGO=steamos
VARIANT_ID=steamdeck
BUILD_ID=20221005.1
VERSION_ID=3.3.2
```
just taking some stabs in the dark here lol


EDIT: NVM looks like it's not even going into the `steamdedeck function` added some debug lines and it didn't print

**Comment by zany130** [comment]
by moving the call to steamdedeck to above load language I was able to get it to load though it looks like its complaining about something?

```
(deck@steamdeck Applications)$ ./steamtinkerlaunch 
HELLO!!!!
Debug entered steamdedeckt function
./steamtinkerlaunch: line 3464: [: : integer expression expected
No summary specified.
 on Steam Deck
./steamtinkerlaunch: line 3464: [: : integer expression expected
No summary specified.


Dependency 'wget' already installed, nothing to do.
./steamtinkerlaunch: line 3464: [: : integer expression expected
No summary specified.

Downloading dependency 'innoextract-1.9-5-x86_64.pkg.tar.zst'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  209k  100  209k    0     0   173k      0  0:00:01  0:00:01 --:--:--  173k
Successfully downloaded innoextract-1.9-5-x86_64.pkg.tar.zst!
Extracting dependency 'innoextract-1.9-5-x86_64.pkg.tar.zst'...
Successfully extracted 'innoextract-1.9-5-x86_64.pkg.tar.zst' to '/home/deck/stl/deps'
./steamtinkerlaunch: line 3464: [: : integer expression expected
No summary specified.

Downloading dependency 'cabextract-1.9.1-2-x86_64.pkg.tar.zst'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36549  100 36549    0     0  64832      0 --:--:-- --:--:-- --:--:-- 64803
Successfully downloaded cabextract-1.9.1-2-x86_64.pkg.tar.zst!
Extracting dependency 'cabextract-1.9.1-2-x86_64.pkg.tar.zst'...
Successfully extracted 'cabextract-1.9.1-2-x86_64.pkg.tar.zst' to '/home/deck/stl/deps'

./steamtinkerlaunch: line 3464: [: : integer expression expected
No summary specified.

./steamtinkerlaunch: line 3464: [: : integer expression expected

./steamtinkerlaunch: line 3464: [: : integer expression expected

./steamtinkerlaunch: line 3464: [: : integer expression expected

./steamtinkerlaunch: line 3464: [: : integer expression expected
No summary specified.

Finished updating SteamTinkerLaunch ('v11.12.20221109-1')!
./steamtinkerlaunch: line 9017: /home/deck/Applications/misc/steamtinkerlaunch.svg: No such file or directory
Wed Nov  9 01:25:15 PM EST 2022 INFO - main - No arguments provided. See 'steamtinkerlaunch --help' for possible command line parameters
```

the HELLO and debug lines where echo lines I added for debugging :)

**Comment by sonic2kk** [comment]
Thanks for testing some more! I pushed a change that may resolve the complains. You may need to run `git reset --hard` locally to be able to update.

The error about integer expression is because `STLQUIET` isn't set (maybe because you moved `steamdedeck` it couldn't see it) but to be safe I added it at the top of the script so it'll always be set.

The error "No summary specified" is from `notify-send`, it returns this when it can't find a string (which in this case it probably can't find the STL Steam Deck install notifier language strings)

**Comment by sonic2kk** [comment]
Ah! I just seen your other comment, sorry (tired after work today...)

> im thinking this may be faling if [ -f "/etc/os-release" ] && grep -q "steamdeck" "/etc/os-release"; then ONSTEAMDECK=1
>
> as this produces nothing (is it supposed to?)

The `-q` switch for `grep` means it won't print the output

**Comment by sonic2kk** [comment]
Ah! Now I remember why i had the local install check where I did - I put it there so the paths would be set before the language file was loaded. But it should probably work fine now that I think about it, I think loadLangFile has some checks for where and how to load the language files...

**Comment by zany130** [comment]
> Thanks for testing some more! I pushed a change that may resolve the complains. You may need to run `git reset --hard` locally to be able to update.

wouldn't removing 
`~/stl/`
`~/.config/steamtinkerlaunch/`
`/dev/shm/steamtinkerlaunch/`
then redownloading the script be fine?

i did that and I still get the same thing as above

```
(deck@steamdeck ~)$ Applications/steamtinkerlaunch 
Wed Nov  9 01:35:33 PM EST 2022 ERROR - loadLanguage - ###############################
Wed Nov  9 01:35:33 PM EST 2022 ERROR - loadLanguage - No language file could be loaded! For the initial setup at least one file (default english) is required
Wed Nov  9 01:35:33 PM EST 2022 ERROR - loadLanguage - You can ether copy a valid file to '/home/deck/.config/steamtinkerlaunch/lang' or '/usr/share/steamtinkerlaunch/lang' or provide an absolute path via command line using the lang= option
Wed Nov  9 01:35:33 PM EST 2022 ERROR - loadLanguage - ###############################
(deck@steamdeck ~)$ cat /dev/shm/steamtinkerlaunch/steamtinkerlaunch.log 
Wed Nov  9 01:35:32 PM EST 2022 INFO - setflatpak - started SteamTinkerLaunch from Applications/steamtinkerlaunch
Wed Nov  9 01:35:32 PM EST 2022 INFO - initAID - Set AID to PLACEHOLDERAID '31337'
Wed Nov  9 01:35:32 PM EST 2022 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Wed Nov  9 01:35:32 PM EST 2022 INFO - loadLangFile - Language from command line is 'english'
Wed Nov  9 01:35:32 PM EST 2022 INFO - loadLangFile - SYSTEMSTLCFGDIR is '/usr/share/steamtinkerlaunch'
Wed Nov  9 01:35:32 PM EST 2022 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Wed Nov  9 01:35:32 PM EST 2022 ERROR - loadLangFile - Language file '/usr/share/steamtinkerlaunch/lang//english.txt' could not be found
Wed Nov  9 01:35:33 PM EST 2022 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Wed Nov  9 01:35:33 PM EST 2022 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Wed Nov  9 01:35:33 PM EST 2022 ERROR - loadLanguage - ###############################
Wed Nov  9 01:35:33 PM EST 2022 ERROR - loadLanguage - No language file could be loaded! For the initial setup at least one file (default english) is required
Wed Nov  9 01:35:33 PM EST 2022 ERROR - loadLanguage - You can ether copy a valid file to '/home/deck/.config/steamtinkerlaunch/lang' or '/usr/share/steamtinkerlaunch/lang' or provide an absolute path via command line using the lang= option
Wed Nov  9 01:35:33 PM EST 2022 ERROR - loadLanguage - ###############################
```

maybe i also need the lang files downloaded? but i don't remember that being the case or it being in the wiki....

**Comment by sonic2kk** [comment]
Ah! If you don't have it, you need a full SteamTinkerLaunch download. So either do a full `git clone` or download from the Releases page. Then double click or `./steamtinkerlaunch` :-)

SteamTinkerLaunch will "download" the language files in that it'll clone itself to `$HOME/stl/prefix` and that'll take in the language files, but STL may also want language files in the same folder as the script. I didn't test with just the script on its own

**Comment by zany130** [comment]
ahh ok i was under the assumption that it would auto-download the lang files for you and you just needed the main file. my bad. Yes git cloning the whole thing does work

going to try protonup now too

**Comment by sonic2kk** [comment]
Ahhh awesome! I guess a check could be added for the langfiles if they aren't in the same directory as the script, but at the moment that sounds like a lot to me. Maybe in future I'll take a look at implementing it, it wouldn't be an unwelcome feature. But it's not really what I would call "expected" usage - It likely worked because as I don't think there were many checks for langfiles.

I added a lot more complexity to the SteamTinkerLaunch Steam Deck install process in #629 - A bit more probably wouldn't be the end of the world but right at this moment there are other things on my mind to add first. Sorry about that, but thank you for testing as I had no idea about this use-case and that this use-case could be problematic. I tried to cover a lot in my original Steam Deck improvements PR but I missed that :sweat: 

<hr>

Thanks for all the testing and for going ahead and trying ProtonUp-Qt again! I'm currently working on a PR to improve STL support with ProtonUp-Qt in-between adding HMM support to STL :-)

**Comment by zany130** [comment]
no worries I re-read the wiki and yeah it does mention downloading the whole release I just remember (back when frostwork first added deck support) it is just downloading the script and it would auto-download everything

proton up is still hanging on extracting stl(git) but that may be more of a bug for protonup than here?

**Comment by sonic2kk** [comment]
> I just remember (back when frostwork first added deck support) it is just downloading the script and it would auto-download everything

I will keep in mind about adding support for loading the language files after the install from source if they can't be found. Probably at least `english.txt` would need to be fetched in that case, since we need a lang file to load the notifier text. It could end up being quite complex to implement with a lot of conditional checks. It's not something I'm gonna rule out entirely but it's just a "not right now" kind of thing :sweat_smile: 

> proton up is still hanging on extracting stl(git) but that may be more of a bug for protonup than here?

Yeah that's been reported before and I think it's an issue with the Flatpak that hasn't been rolled out into a full release yet. You could try ProtonUp-Qt from source and see if you can install it that way. And though it's been reported before I think this confirms that the current implementation at least on Flatpak Steam Deck has some problem. But I think it's fixed in source, at least on my Steam Deck running from source it seems to work.

**Comment by sonic2kk** [comment]
Before closing, could you also check the `global.conf` and see if the paths to the `GLOBALCOLLECTIONDIR` are set correctly? They should be pointing probably to `/home/deck/stl/prefix/<some folder>` :-)

**Comment by zany130** [comment]
this?
`GLOBALCOLLECTIONDIR="/home/deck/stl/prefix/collections"`

Also yeah was able to get it installed fine with the latest prontonup-qt git

**Comment by sonic2kk** [comment]
> this?
> ` GLOBALCOLLECTIONDIR="/home/deck/stl/prefix/collections"`

Yup, perfect. Thank you! :sweat_smile: 

> Also yeah was ablt e to get it installed fine with the latest prontonup-qt git

Okay, phew, so this is something that'll be resolved in the next release of ProtonUp-Qt.

Awesome, thank you so much for your work testing this! *Closing...*
