### ISSUE TITLE
Installing vortex stuck at 0%

### ISSUE THREAD

**Issue by TRPB** [sonic2kk/steamtinkerlaunch#846]
## System Information
- SteamTinkerLaunch version: steamtinkerlaunch-v12.12
- Distribution:  Arch Linux
- Installation Method: AUR
- 
## Issue Description

I clicked on "Install Vortex" after launching Skyrim, it shows the window but hangs at 0% 

## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11929751/steamtinkerlaunch.log)

Same thing happens if I run `steamtinkerlaunch vortex install` from the command line. I've tried selecting a different proton version, it doesn't make any difference.

**Comment by sonic2kk** [comment]
Did you try STL from git? The issue template suggests [checking the changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog#changes-in-latest-master) before making an issue, and various Vortex-related issues were fixed in git.

**Comment by sonic2kk** [comment]
I did a test with SteamTinkerLaunch v14.0.20230626-3 (2d5ed122cb47eafea4b3e9f69ff93273016bd6a5) and Vortex v1.8.5 installed fine (I'm also running Arch Linux). If I recall previous issues (only reported on SteamOS 3.X before) were related to .NET 4.8 not installing correctly, and this is no longer required for Vortex and so no longer installed with SteamTinkerLaunch git.

In general, if you experience an issue with STL, it's best to check if it also occurs on the latest git, as stable releases are often out-of-date, and because I'm low on time and motivation I don't plan to make another stable release for a while.

**Comment by sonic2kk** [comment]
Did you get a chance to test this with STL from git? It's available from the AUR, ProtonUp-Qt, and can also be installed manually with `sudo make install` (and uninstalled with `sudo make uninstall`).

**Comment by thedavidweng** [comment]
encountered the same problem, tried the latest git (v14.0.20230702-3), still broken

**Comment by sonic2kk** [comment]
Please provide more information like your distro and installation method, as well as a log file for a full Vortex installation attempt.

Vortex installation works for me so I can't troubleshoot much without that information.

**Comment by sonic2kk** [comment]
I re-read the opening issue's log and it looks like the Proton version for Vortex may not be set. Since `jq` is strangely not installed, the GE-Proton version to install Vortex cannot be found. @TRPB I would suggest checking the Vortex Proton version on the Global Menu. If it's not set or if it's set to something strange, change it to something like Proton 8.0-2d, or the latest GE-Proton. I'd also recommend installing `jq`.

@thedavidweng You could check if you have a similar issue (for example, `jq` may be missing). Providing a log of an installation attempt would also help.

Getting stuck at 0% suggests that the installation isn't even getting to the point of running Wine, which is what prompted me to re-check the log.

**Comment by spiderworm** [comment]
Yesterday I tried installing Vortex through SteamTinkerLaunch on my Steam Deck and was stuck with this very same issue.

Today I was trying again and noticed that a window had opened up that I couldn't get to. It took some maximizing and minimizing of windows and moving then around until I managed to get to this little window that was more like an alert from the Vortex installer. It said something like "Vortex requires Windows 10 to run. Click Abort to cancel installation or Ignore to continue anyways".  I clicked Ignore and from what I can tell it did install.

However, Vortex won't start. Attempting to start it gets me a quick SteamTinkerLaunch progress bar window that goes away quickly and no Vortex windows show up.

**Comment by sonic2kk** [comment]
Did you do a fresh install from SteamTinkerLaunch from git? Noting that issues with Vortex were fixed from git, see the changelog: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog#features

If things are still broken, then oh well. I am absolutely done with trying to fix Wine issues with Vortex, someone else needs to step up and maintain this. I don't use Vortex, I am tired of trying to maintain compatibility with software I actively tell people not to use. To echo what I said in another issue, at this point in STL's life, **I would prefer PRs rather than issues**.

**Comment by sonic2kk** [comment]
Closing due to lack of response from OP. If you still experience this, a PR or an issue **after thorough investigation only** would be welcome where you have a good idea of the underlying cause or even a potential fix. I absolutely refuse to test anything related to modding on my Steam Deck in the interest of keeping it clean, so investigation from technical users (the target audience for SteamTinkerLaunch) is necessary.

**Comment by dolphin-evorobey** [comment]
@spiderworm hey mate, looks like i have same issue, stuck on 0 on my SD, but i cant find any dialog window to click ignore(( trying in game mode and desktop mode, same thing(( any ideas?

**Comment by sonic2kk** [comment]
Like the above, are you sure you're using SteamTinkerLaunch from git? Are you sure the Steam Deck still has `jq`? If you're using SteamTinkerLaunch v12.12, that's probably not going to work. Did you check to see if Vortex is generally broken under Wine, and if using a different version fixes the issue if you're using STL-git?

Either way, Vortex support is an incredibly low priority for STL (I don't like, use, or endorse it, nor did I write the support for it)  and Steam Deck even moreso is a low development priority.

**Comment by dolphin-evorobey** [comment]
@sonic2kk yep thanks, now i'm read wiki and switching to MO2, too much problems with vortex

**Comment by sonic2kk** [comment]
Just out of curiosity, does Vortex with SteamTinkerLaunch-git not work on SteamOS anymore (right now, that would be SteamTinkerLaunch v14.0.20230919-2)? Testing with a clean Vortex install prefix and a known working Proton version (GE-Proton8-2 and up)+Vortex version (in case Vortex is broken under Wine again). 

It works on the Linux Desktop (the primary development target and target audience for STL) but the Steam Deck has some odd problems, probably related to whatever mixture of pinned libraries they're using. I spent a *lot* of work trying to get Vortex working on SteamOS by doing a bunch of conditionals with when to use/not use the Steam Linux Runtime during installation and it worked as of July, but I haven't tested personally ever, and there hasn't been testing by another user since Vortex 1.8.0.

**Comment by sonic2kk** [comment]
On a related note (for yourself or anyone who stumbles across this), there are a couple of things to be aware of:
- Regardless of any other factors, it is always a good idea to use the latest SteamTinkerLaunch-git on SteamOS, as well as the latest Steam Beta (the latter should be the case regardless, there is no reason to stay on the Steam Client Stable on any platform)
- Launching third-party programs such as games from MO2 and custom commands. The issue with MO2 launching games on SteamOS had little information but this works on the Linux Desktop, so it is likely no SteamTinkerLaunch issue
- Bugs with usability of software under Wine aren't SteamTinkerLaunch's responsibility to fix, as this is just a Bash script, there aren't any Wine Devs here
- Steam Deck is a low priority for SteamTinkerLaunch, try to submit fixes instead of issues for Steam Deck specific problems where possible, as I am not in a position to troubleshoot problems on Steam Deck. Furthermore, when possible test on your Linux PC to see if the issue occurs there (you should have a Linux PC if you're using SteamTinkerLaunch, as Steam Deck support is primarily intended for Linux Desktop users who have specific use-cases in mind for STL on SteamOS).
